---
sidebar: sidebar 
permalink: modern-apps/fpd-ai-dl-design.html 
keywords: flexpod, cisco, ai, ml, data, center, deep, learning, design 
summary: 'Dans ce document, nous proposons des informations de conception relatives à l"intégration de la plateforme Cisco UCS C480 ML M5 à la solution FlexPod Datacenter afin de proposer une approche unifiée qui unifie les fonctionnalités d"IA et DE ML dans l"infrastructure convergée.' 
---
= FlexPod Datacenter pour l'IA et LE ML associés à Cisco UCS 480 ML pour le deep learning - Design
:allow-uri-read: 


Haseeb Niazi, Cisco Arvind Ramakrishnan, NetApp

[role="lead"]
Dans ce document, nous proposons des informations de conception relatives à l'intégration de la plateforme Cisco UCS C480 ML M5 à la solution FlexPod Datacenter afin de proposer une approche unifiée qui unifie les fonctionnalités d'IA et DE ML dans l'infrastructure convergée. Les clients peuvent ainsi gérer les serveurs à l'aide de fonctionnalités combinées d'IA et DE ML et des outils familiers qu'ils utilisent pour gérer les systèmes FlexPod classiques. Ils peuvent ainsi réduire de manière significative les charges administratives et le coût de déploiement de la plateforme de deep learning. Le design présenté dans ce CVD inclut également d'autres plateformes Cisco UCS, comme le serveur C220 M5 avec deux processeurs graphiques NVIDIA T4 et le serveur C240 M5 équipé de deux cartes PCIe NVIDIA V100 32 Gb comme options supplémentaires pour gérer simultanément les charges de travail d'IA et DE ML.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_c480m5l_aiml_design.html["FlexPod Datacenter pour l'intelligence artificielle et LE MACHINE LEARNING associés à Cisco UCS 480 ML pour le deep learning - Design"^]
