---
sidebar: sidebar 
permalink: express/express-nva-1154-deploy.html 
keywords: flexpod, cisco, express, vmware, vsphere, ucs, aff, fas, deployment, nva 
summary: 'La solution FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et NetApp AFF/FAS exploite des serveurs lames Cisco UCS Mini avec serveurs lames B200 M5, des interconnexions de fabric dans le châssis Cisco UCS 6324, des commutateurs Cisco Nexus 31108PC-V ou d"autres commutateurs compatibles.' 
---
= FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et NetApp AFF/FAS - NVA - déploiement
:allow-uri-read: 


Jyh-shing Chen, NetApp

La solution FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et NetApp AFF/FAS exploite des serveurs lames Cisco UCS Mini avec serveurs lames B200 M5, des interconnexions de fabric dans le châssis Cisco UCS 6324, des commutateurs Cisco Nexus 31108PC-V ou d'autres commutateurs compatibles, et NetApp AFF A220, C190 ou la paire haute disponibilité des contrôleurs FAS2700, Qui exécute le logiciel de gestion des données NetApp ONTAP 9.7. Ce document de déploiement d'architecture vérifiée NetApp (NVA) détaille les étapes nécessaires à la configuration des composants d'infrastructure et au déploiement de VMware vSphere 7.0 et des outils associés pour créer une infrastructure virtuelle FlexPod Express hautement fiable et disponible.

link:https://www.netapp.com/pdf.html?item=/media/21938-nva-1154-DEPLOY.pdf["FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et NetApp AFF/FAS - NVA - déploiement"^]
