---
sidebar: sidebar 
permalink: express/express-c-series-aff220-design_technology_requirements.html 
keywords: express, requirements, technology, AFF A220, UCS C220 M5, Nexus 3172P switch, Virtual Interface Card, VIC 1387, C220 M5 Rack Server, CVR-QSFP-SFP10G adapter 
summary: 'FlexPod Express requiert une combinaison de composants matériels et logiciels qui dépend de l"hyperviseur et de la vitesse réseau sélectionnés. En outre, FlexPod Express dispose des composants matériels requis pour ajouter des nœuds d"hyperviseur au système par unités deux.' 
---
= Exigences technologiques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


FlexPod Express requiert une combinaison de composants matériels et logiciels qui dépend de l'hyperviseur et de la vitesse réseau sélectionnés. En outre, FlexPod Express dispose des composants matériels requis pour ajouter des nœuds d'hyperviseur au système par unités deux.



== Configuration matérielle requise

Quel que soit l'hyperviseur choisi, toutes les configurations FlexPod Express utilisent le même matériel. Par conséquent, même si les exigences de l'entreprise évoluent, les deux hyperviseurs peuvent s'exécuter sur le même matériel FlexPod Express.

Le tableau suivant répertorie les composants matériels requis pour toutes les configurations FlexPod Express et pour implémenter la solution. Ils peuvent varier selon la mise en œuvre de la solution et les besoins du client.

[cols="50,50"]
|===
| Sous-jacent | Quantité 


| Cluster à deux nœuds AFF A220 | 1 


| Serveur Cisco UCS C220 M5 | 2 


| Commutateur Cisco Nexus 3172P | 2 


| Carte Cisco UCS Virtual interface Card (VIC) 1387 pour serveur en rack Cisco UCS C220 M5 | 2 


| Adaptateur Cisco CVR-QSFP-SFP10G | 4 
|===


== Configuration logicielle requise

Les tableaux suivants répertorient les composants logiciels requis pour l'implémentation des architectures de la solution FlexPod Express.

Le tableau suivant répertorie la configuration logicielle requise pour l'implémentation FlexPod Express de base.

[cols="33,33,33"]
|===
| Logiciel | Version | Détails 


| Contrôleur de gestion intégrée Cisco (CIMC) | 3.1.3 | Pour serveurs en rack C220 M5 


| Cisco NX-OS | nxos.7.0.3.I7.5.bin | Pour commutateurs Cisco Nexus 3172P 


| NetApp ONTAP | 9.4 | Pour les contrôleurs AFF A220 
|===
Le tableau suivant répertorie les logiciels requis pour toutes les implémentations VMware vSphere sur FlexPod Express.

[cols="50,50"]
|===
| Logiciel | Version 


| Appliance VMware vCenter Server | 6.7 


| VMware vSphere ESXi | 6.7 


| Plug-in NetApp VAAI pour ESXi | 1.1.2 
|===
link:express-c-series-aff220-design_design_choices.html["Suivant : choix de conception."]
