---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: 'Ce document décrit en détail la configuration d"un système FlexPod Express entièrement redondant et hautement disponible. Pour refléter cette redondance, les composants configurés à chaque étape sont appelés composant A ou composant B.' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Ce document décrit en détail la configuration d'un système FlexPod Express entièrement redondant et hautement disponible. Pour refléter cette redondance, les composants configurés à chaque étape sont appelés composant A ou composant B. Par exemple, les contrôleurs A et B identifient les deux contrôleurs de stockage NetApp provisionnés dans ce document. Les commutateurs A et B identifient une paire de commutateurs Cisco Nexus.

Ce document décrit également les étapes de provisionnement de plusieurs hôtes Cisco UCS, identifiés de manière séquentielle en tant que serveur A, serveur B, etc.

Pour indiquer que vous devez inclure dans une étape des informations concernant votre environnement, `\<<text>>` s'affiche dans le cadre de la structure de commande. Reportez-vous à l'exemple suivant pour le `vlan create` commande :

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
Ce document vous permet de configurer entièrement l'environnement FlexPod Express. Dans ce processus, plusieurs étapes nécessitent l'insertion de conventions d'appellation spécifiques au client, d'adresses IP et de schémas de réseau local virtuel (VLAN). Le tableau suivant décrit les VLAN nécessaires au déploiement, comme indiqué dans ce guide. Ce tableau peut être complété en fonction des variables spécifiques du site et utilisé pour mettre en œuvre les étapes de configuration du document.


NOTE: Si vous utilisez des VLAN de gestion intrabande et hors bande distincts, vous devez créer une route de couche 3 entre eux. Pour cette validation, un VLAN de gestion commun a été utilisé.

|===
| Nom du VLAN | Objectif VLAN | ID VLAN |  


| VLAN de gestion | VLAN pour les interfaces de gestion | 3437 | VSwitch0 


| VLAN NFS | VLAN pour le trafic NFS | 3438 | VSwitch0 


| VLAN VMware vMotion | VLAN désigné pour le déplacement de machines virtuelles (VM) d'un hôte physique à un autre | 3441 | VSwitch0 


| VLAN trafic des VM | VLAN pour le trafic des applications des VM | 3442 | VSwitch0 


| ISCSI-A-VLAN | VLAN pour le trafic iSCSI sur la structure A | 3439 | VSwitch iSciBootvSwitch 


| ISCSI-B-VLAN | VLAN pour le trafic iSCSI sur la structure B | 3440 | VSwitch iSciBootvSwitch 


| VLAN natif | VLAN auquel des trames non marquées sont attribuées | 2 |  
|===
Les numéros de VLAN sont nécessaires dans toute la configuration de FlexPod Express. Les VLAN sont appelés `\<<var_xxxx_vlan>>`, où `xxxx` Utilise le VLAN (par exemple iSCSI-A).

Deux vswitches sont créés dans cette validation.

Le tableau suivant répertorie les vswitches de solution.

|===
| Nom du vSwitch | Adaptateurs actifs | Ports | MTU | Équilibrage de la charge 


| VSwitch0 | Vmnic2 et vmnic4 | par défaut (120) | 9000 | Route basée sur un hachage IP 


| VSwitch iSciBootvSwitch | Vmnic3, vmnic5 | par défaut (120) | 9000 | Route basée sur l'ID de port virtuel d'origine. 
|===

NOTE: La méthode de hachage IP d'équilibrage de charge nécessite une configuration correcte pour le commutateur physique sous-jacent à l'aide de SRC-DST-IP EtherChannel avec un canal de port statique (mode activé). En cas de connectivité intermittente due à une éventuelle mauvaise configuration du commutateur, arrêtez temporairement l'un des deux ports de liaison montante associés sur le commutateur Cisco pour restaurer la communication vers le port vmkernel de gestion ESXi tout en dépannant les paramètres du canal de port.

Le tableau suivant répertorie les machines virtuelles VMware créées.

|===
| Description de la machine virtuelle | Nom d'hôte 


| Serveur VMware vCenter | FlexPod-VCSA 


| Virtual Storage Console | FlexPod-VSC 
|===