---
sidebar: sidebar 
permalink: express/express-direct-attach-aff220-deploy_program_summary.html 
keywords: flexpod, express, vmware, vsphere, aff, direct, attached, ip, based, storage 
summary: 'FlexPod Express est une architecture préconçue et conforme aux bonnes pratiques. Elle repose sur la gamme Cisco Unified Computing System (Cisco UCS), la gamme de commutateurs Cisco Nexus et les technologies de stockage NetApp. Les plateformes FlexPod Datacenter et FlexPod Express sont optimales pour la virtualisation, les systèmes d"exploitation sans système d"exploitation et les charges de travail d"entreprise.' 
---
= NVA-1131-DEPLOY : FlexPod Express avec VMware vSphere 6.7U1 et NetApp AFF A220 avec stockage basé sur IP à connexion directe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Sree Lakshmi Lanka, NetApp

Les tendances du secteur témoignent d'une vaste transformation des data centers en infrastructure partagée et cloud computing. Elles recherchent par ailleurs une solution simple et efficace pour les succursales et les bureaux distants, exploitant la technologie qu'elles connaissent bien dans leur data Center.

FlexPod Express est une architecture préconçue et conforme aux bonnes pratiques. Elle repose sur la gamme Cisco Unified Computing System (Cisco UCS), la gamme de commutateurs Cisco Nexus et les technologies de stockage NetApp. Ce sont les composants d'un système FlexPod Express qui ressemble à ceux de leurs homologues FlexPod Datacenter, ce qui favorise une synergie de gestion dans l'ensemble de l'environnement d'infrastructure IT à plus petite échelle. Les plateformes FlexPod Datacenter et FlexPod Express sont optimales pour la virtualisation, les systèmes d'exploitation sans système d'exploitation et les charges de travail d'entreprise.

Les solutions FlexPod Datacenter et FlexPod Express proposent une configuration de base et offrent la polyvalence nécessaire pour faire face à des cas d'utilisation et à des exigences très variés. Les clients FlexPod Datacenter existants peuvent gérer leur système FlexPod Express avec les outils auxquels ils sont habitués. Les nouveaux clients FlexPod Express peuvent facilement s'adapter à la gestion d'FlexPod Datacenter à mesure que leur environnement se développe.

FlexPod Express est une infrastructure idéale pour les bureaux distants, les succursales et les moyennes entreprises. Il s'agit également d'une solution idéale pour les clients qui souhaitent mettre en place une infrastructure pour une charge de travail dédiée.

FlexPod Express offre une infrastructure facile à gérer qui convient à quasiment tous les workloads.
