---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_solution_overview.html 
keywords: flexpod, datacenter, technical specifications, platform, architecture 
summary: 'La plateforme FlexPod est une architecture de centre de données prédéfinie et conforme à la bonne pratique, construite sur le Cisco Unified Computing System (Cisco UCS), la famille de commutateurs Cisco Nexus et les contrôleurs de stockage NetApp (NetApp AFF, ASA, FAS ou systèmes AFX).' 
---
= Caractéristiques techniques des data centers FlexPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La plateforme FlexPod est une architecture de centre de données prédéfinie et conforme à la bonne pratique, construite sur le Cisco Unified Computing System (Cisco UCS), la famille de commutateurs Cisco Nexus et MDS (pour FC), et les contrôleurs de stockage NetApp (systèmes AFF, ASA, FAS ou AFX).

FlexPod est une plateforme adaptée pour exécuter divers hyperviseurs de virtualisation, systèmes d'exploitation bare-metal, environnements conteneurisés et charges de travail d'entreprise. FlexPod fournit non seulement une configuration de base, mais aussi la flexibilité nécessaire pour être dimensionnée et optimisée afin de répondre à de nombreux cas d'utilisation et exigences différents.


NOTE: Avant de commander une configuration complète FlexPod, consultez la  http://www.netapp.com/us/technology/flexpod["NetApp FlexPod Page d'accueil"^] dernière version de ces spécifications techniques.

link:dc-tech-spec_flexpod_platforms.html["Ensuite : plateformes FlexPod."]
