---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct 
summary: 'Cisco a largement contribué à la conception et à l"architecture de FlexPod, couvrant à la fois les couches de calcul et de réseau de la solution. Cette section décrit les options Cisco UCS et Cisco Nexus disponibles pour FlexPod.' 
---
= Composants Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco a largement contribué à la conception et à l'architecture de FlexPod, couvrant à la fois les couches de calcul et de réseau de la solution. Cette section décrit les options Cisco UCS, Nexus et MDS disponibles pour FlexPod.



[[cisco-ucs-fabric-interconnect-options]]
== Options d'interconnexion de fabric Cisco UCS

Des interconnexions de fabric redondantes sont requises dans l'architecture FlexPod. Lorsque vous ajoutez plusieurs châssis Cisco UCS à une paire d'interconnexions de fabric, n'oubliez pas que le nombre maximal de châssis dans un environnement est déterminé par une limite architecturale et par un nombre de ports.

Les références indiquées dans le tableau ci-dessous concernent les interconnexions de base. Elles n'incluent pas le bloc d'alimentation (PSU), les modules SFP+, QSFP+ ni les modules d'extension.

|===
| Interconnexion de fabric Cisco UCS | Numéro de référence | Caractéristiques techniques 


| Cisco UCS 6664 | UCS-FI-6664-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf["Fabric Interconnect Cisco UCS de la série 6600"] 


| Cisco UCS 6652 | UCS-FI-6652-U 


| Cisco UCS 6536 | UCSX-FI-6536-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf["Interconnexion de fabric Cisco UCS 6536"] 


| Cisco UCS 6454 | UCS-FI-6454-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf["Fabric Interconnect Cisco UCS série 6400"] 


| Cisco UCS 64108 | UCS-FI-64108-U 


| Interconnexion de structure UCS 9108 100G (Cisco UCS X-Series Direct) | UCSX-S9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Interconnexion de fabric Cisco UCS 9108"] 
|===


[[cisco-ucs-x-series-chassis-option]]
== Option de châssis Cisco UCS X-Series

Pour utiliser les nœuds de calcul Cisco UCS X-Series, vous devez disposer d'un châssis Cisco UCS X-Series. Le tableau suivant décrit l'option de châssis Cisco UCS X-Series.

|===
| Des serveurs lames Cisco UCS X-Series | Numéro de référence | Caractéristiques techniques 


| Cisco UCS X9508 Châssis | NGCX-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317["Cisco UCS X9508 Châssis"] 
|===
Chaque châssis Cisco UCS 9508 doit disposer de deux modules de structure intelligente Cisco UCS 9108 pour assurer une connectivité redondante avec les interconnexions de fabric.



[[cisco-ucs-x-series-device-options]]
== Options de périphériques Cisco UCS X-Series

Les nœuds de calcul Cisco UCS X-Series sont disponibles avec plusieurs options de CPU, de mémoire et d'E/S. Les références répertoriées dans le tableau suivant concernent le nœud de base. Ils ne comprennent pas le processeur, la mémoire, les disques ou les cartes d'adaptateur mezzanine. De nombreuses options de configuration sont disponibles et prises en charge dans l'architecture FlexPod.

|===
| Nœuds de calcul Cisco UCS X-Series | Numéro de référence | Caractéristiques techniques 


| Cisco UCS X210c M7 | UCSX-210C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Cisco UCS X210c M7 Nœud de calcul"] 


| Cisco UCS X210c M8 | UCSX-210C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Cisco UCS X210c M8 Nœud de calcul"] 


| Cisco UCS X215c M8 | UCSX-215C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Cisco UCS X215c M8 Nœud de calcul"] 


| Cisco UCS X410c M7 | UCSX-410C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Cisco UCS X410c M7 Nœud de calcul"] 


| Cisco UCS X410c M8 | UCSX-410C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Cisco UCS X410c M8 Nœud de calcul"] 
|===
Le tableau ci-dessous répertorie les nœuds PCI Express disponibles pour le châssis Cisco UCS X-Series.

|===
| Nœuds PCIe Cisco UCS X-Series | Numéro de référence | Caractéristiques techniques 


| Cisco UCS X580p Nœud PCIe | UCSX-580P-U | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html["Cisco UCS X580p Nœud PCIe"] 


| Cisco UCS X440p Nœud PCIe | UCSX-440P | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html["Cisco UCS X440p Nœud PCIe"] 
|===
Le tableau ci-dessous répertorie les modules X-Fabric disponibles pour le châssis Cisco UCS X-Series.

|===
| Modules Cisco UCS X-Series X-Fabric | Numéro de référence | Caractéristiques techniques 


| Module de fabric intelligent Cisco UCS 9108 | UCSX-I-9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf["Module de fabric intelligent Cisco UCS 9108"] 


| Module X-Fabric Cisco UCS X9516 | UCSX-FS-9516 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html["Module X-Fabric Cisco UCS X9516"] 


| Module X-Fabric Cisco UCS X9416 | UCSX-F-9416 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665["Module X-Fabric Cisco UCS X9416"] 
|===


[[cisco-ucs-x-series-modular-system]]
== Système modulaire Cisco UCS X-Series

Le système modulaire Cisco UCS X-Series commence avec le châssis serveur Cisco UCS X9508, conçu pour être adaptable et prêt pour l'avenir. Le châssis dispose d'une architecture Ethernet unifiée avec les modules Cisco UCS Intelligent Fabric et la technologie Cisco UCS X-Fabric pour d'autres technologies. À l'arrière supérieur du châssis se trouvent deux modules Intelligent Fabric qui connectent le châssis aux Cisco UCS 6400, 6500 et UCS 6600 Series Fabric Interconnects en amont.

Pour un aperçu rapide des capacités et fonctionnalités de Cisco UCS X-Series, consultez link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html["Cisco UCS X-Series Modular System - Aperçu"^].

Les nœuds de calcul Cisco UCS X215c M8, Cisco UCS X210c et Cisco UCS X410c offrent les fonctionnalités des serveurs lames et rack en proposant une densité de calcul, une capacité de stockage et une extensibilité dans un format unique.

Le nœud PCIe Cisco UCS X440p prend en charge l’ajout de GPU avec PCIe Gen 4.0 grâce au module Cisco UCS X9416 X-Fabric. Le nœud PCIe Cisco UCS X580p prend en charge l’ajout de GPU avec PCIe Gen 5.0 grâce au module Cisco UCS X9516 X-Fabric.

Pour plus d'informations sur les composants de la solution Cisco UCS X-Series Modular System, veuillez vous référer aux spécifications techniques de chacun de ces composants dans les sections ci-dessus.


NOTE: Pour consulter les spécifications techniques complètes du système modulaire Cisco UCS X-Series, veuillez vous référer au lien suivant :link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html["Système modulaire Cisco UCS X-Series"^]



[[cisco-ucs-x-series-direct-options]]
== Options directes Cisco UCS X-Series

Cisco UCS X-Series Direct est une nouvelle architecture qui intègre une paire de Cisco UCS Fabric Interconnect 9108 100G avec le châssis Cisco UCS X9508 et les nœuds de calcul Cisco UCS X-Series pour fournir la solution UCS X-Series Direct.

Pour un aperçu rapide des capacités et fonctionnalités de Cisco UCS X-Series, consultez link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html["Cisco UCS X-Series Direct Aperçu"^].

Cisco UCS X-Series Direct se compose des éléments suivants :

* Interconnexion de fabric Cisco UCS 9108 100G
* Cisco UCS X9508 Châssis
* Cisco UCS X-Series Nœuds de calcul
* Composants optionnels :
+
** Nœuds PCIe et module X-Fabric
** Deuxième châssis Cisco UCS X9508 avec nœuds de calcul X-Series et modules de structure intelligente Cisco UCS 9108-100G et jusqu'à quatre serveurs rack C-Series




Pour plus d'informations sur les composants de la solution Cisco UCS X-Series Direct, veuillez vous référer aux spécifications techniques de chacun de ces composants dans les sections ci-dessus.


NOTE: Veuillez consulter le lien suivant pour obtenir les spécifications techniques complètes de Cisco UCS X-Series Direct : https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html["Fiche technique directe Cisco UCS X-Series"].



[[cisco-ucs-c-series-rack-server-options]]
== Options de serveur rack Cisco UCS C-Series

Les serveurs rack Cisco UCS série C sont disponibles en versions une, deux et quatre unités de rack (RU), avec diverses options de processeur, de mémoire et d'E/S. Les références indiquées dans le deuxième tableau ci-dessous correspondent au serveur de base. Elles n'incluent pas les processeurs, la mémoire, les disques ni les cartes Peripheral Component Interconnect Express (PCIe). De multiples options de configuration sont disponibles et prises en charge dans l'architecture FlexPod.

Le tableau suivant répertorie les options des serveurs en rack Cisco UCS C-Series.

|===
| Serveur rack Cisco UCS C-Series | Numéro de référence | Caractéristiques techniques 


| Cisco UCS C220 M7 | UCSC-C220-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Serveur en rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | UCSC-C220-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Serveur en rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | UCSC-C225-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Serveur en rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | UCSC-C240-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Serveur en rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | UCSC-C240-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Serveur en rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | UCSC-C245-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Serveur en rack Cisco UCS C245 M8"] 
|===
Le tableau suivant répertorie les serveurs rack Cisco UCS série C optimisés pour les cas d'utilisation de l'IA :

|===
| Serveur en rack Cisco UCS C-Series | Numéro de référence | Caractéristiques techniques 


| Cisco UCS C845A M8 | UCSC-C845A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html["Serveur en rack Cisco UCS C845A M8"] 


| Cisco UCS C880A M8 | UCSC-C880A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html["Serveur en rack Cisco UCS C880A M8"] 
|===
Les générations précédentes de serveurs Cisco UCS série C peuvent être utilisées dans l’architecture FlexPod si elles sont prises en charge sur le https://ucshcltool.cloudapps.cisco.com/public/["Liste de compatibilité matérielle et logicielle Cisco UCS"^].



[[cisco-nexus-9000-series-switch-options]]
== Options des commutateurs Cisco Nexus 9000 Series

Des commutateurs redondants Cisco Nexus série 9000 sont requis dans l’architecture FlexPod. Les références indiquées dans le tableau ci-dessous correspondent aux châssis Cisco Nexus série 9000 ; elles n’incluent pas les modules SFP ni les modules Ethernet.

|===
| Cisco Nexus switch - Fixe | Caractéristiques techniques 


| Commutateur Cisco Nexus série 9200 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Commutateurs Cisco Nexus 9200 Series"] 


| Commutateur Cisco Nexus série 9300 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Commutateurs Cisco Nexus 9300 Series"] 
|===
|===
| Cisco Nexus switch - Modulaire | Caractéristiques techniques 


| Commutateur Cisco Nexus série 9400 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385["Commutateurs Cisco Nexus de la gamme 9400"] 


| Commutateur Cisco Nexus série 9500 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html["Commutateurs Cisco Nexus 9500 Series"] 


| Commutateur Cisco Nexus série 9800 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386["Commutateurs Cisco Nexus de la gamme 9800"] 
|===


[[cisco-apic-options]]
== Options APIC Cisco

Cisco APIC est le principal composant architectural de Cisco ACI. Il constitue le point unifié d'automatisation et de gestion de l'infrastructure Cisco ACI.

Pour plus d'informations sur les spécifications des produits APIC, reportez-vous aux tableaux 1 à 3 sur le https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Fiche technique de Cisco application Policy Infrastructure Controller"^].



[[cisco-mds-options]]
== Options Cisco MDS

Bien que les commutateurs Cisco MDS soient un élément optionnel de l’architecture FlexPod, les déploiements utilisant la connectivité SAN Fibre Channel pour un accès au stockage haute performance doivent mettre en œuvre des matrices de commutateurs Cisco MDS redondantes afin de garantir une infrastructure SAN hautement disponible. Le tableau ci-dessous répertorie les commutateurs Cisco MDS pris en charge. Consultez la  https://imt.netapp.com["NetApp IMT"^] et la  https://ucshcltool.cloudapps.cisco.com/public/["Liste de compatibilité matérielle et logicielle Cisco"^] pour obtenir la liste complète des commutateurs SAN pris en charge.

|===
| Commutateur Cisco MDS | Description 


| Commutateurs de structure multicouches Cisco MDS 9100 | http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html["Commutateurs Cisco MDS 9100 Series"] 


| Commutateurs multiservices Cisco MDS 9200 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html["Commutateurs Cisco MDS 9200 Series"] 


| Commutateurs de structure multicouches Cisco MDS 9300 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html["Commutateurs Cisco MDS 9300 Series"] 


| Cisco MDS 9700 Directeurs multicouches | http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html["Commutateurs Cisco MDS série 9700"] 
|===


[[cisco-support-licensing-options]]
== Options de licence de prise en charge par Cisco


NOTE: Il est recommandé de vérifier les exigences de licence auprès de votre représentant commercial Cisco ou NetApp avant de passer commande.

link:https://www.cisco.com/c/dam/en_us/about/doing_business/legal/service_descriptions/docs/solution-support-smart-total-care.pdf["Cisco Solution Support"^] est une offre de service d'assistance technique qui s'applique aux solutions Cisco qui comprennent à la fois du matériel et des logiciels de Cisco uniquement ou de Cisco et des Solution Support Alliance Partners, et qui sont composées exclusivement de produits Cisco et de produits fournis par des fournisseurs tiers (Solution Support Alliance Partner(s)).

Cisco prend en charge les environnements clients complexes grâce à son link:https://www.cisco.com/c/en/us/support/web/tac/technical-services-resource-guide.html["Centre d'assistance technique"]. Cisco Solution Support donne aux clients accès à une équipe d'ingénieurs du TAC, qui constituent le principal point de contact pour les problèmes rencontrés au sein de la solution, ainsi qu'à une assistance produit pour le matériel et les logiciels qui composent la solution.

Cisco utilise le link:https://www.tsanet.org/cisco-tsanet-case-study/["Programme de partenariat TSANet"^] framework pour intégrer les Solution Support Partners dans un groupe privé sur le système TSANet Connect. TSANet Connect offre une méthode cohérente permettant aux ingénieurs de support de collaborer avec les équipes techniques des partenaires, garantissant une communication efficace et une résolution accélérée des problèmes, sans les frictions causées par des tentatives informelles de collaboration avec les partenaires.
