---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_components.html 
keywords: storage, controllers, cluster, aff, asa, fas, afx, ontap, interconnect switches, drives, disk, shelves, licensing, options 
summary: 'Les contrôleurs de stockage NetApp constituent la base du stockage de l"architecture FlexPod pour le stockage des données de démarrage et d"applications. Les composants NetApp sont notamment des contrôleurs de stockage, des commutateurs d"interconnexion de cluster, des disques et des tiroirs disques, ainsi que des options de licence.' 
---
= Composants NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les contrôleurs de stockage NetApp constituent la base du stockage de l'architecture FlexPod pour le stockage des données de démarrage et d'applications. Les composants NetApp sont notamment des contrôleurs de stockage, des commutateurs d'interconnexion de cluster, des disques et des tiroirs disques, ainsi que des options de licence.



[[netapp-storage-controller-options]]
== Options de contrôleurs de stockage NetApp

Des contrôleurs NetApp FAS, AFF, ASA ou AFX redondants sont requis dans l’architecture FlexPod. Les contrôleurs exécutent le logiciel ONTAP. Lors de la commande des contrôleurs de stockage, la version logicielle préférée peut être préchargée sur les contrôleurs. Pour ONTAP, un cluster complet est commandé. Un cluster complet comprend une paire de contrôleurs de stockage et une interconnexion de cluster (avec ou sans commutateur).


NOTE: La configuration sans commutateur n'est prise en charge que pour une configuration à deux nœuds. Les commutateurs d'interconnexion de cluster sont nécessaires pour les configurations à quatre nœuds ou plus, et sont optionnels pour une configuration à deux nœuds.

Différentes options et configurations sont disponibles, en fonction de la plateforme de stockage sélectionnée. Pour plus d'informations sur ces composants supplémentaires, adressez-vous à votre représentant commercial.

Les gammes de contrôleurs répertoriées dans le tableau ci-dessous peuvent être utilisées dans une solution de data Center FlexPod, car leur connexion aux commutateurs Cisco Nexus est transparente. Voir la https://hwu.netapp.com/["NetApp Hardware Universe"^] pour en savoir plus sur la compatibilité de chaque modèle de contrôleur.

|===
| Gamme de stockage NetApp pour FlexPod Datacenter | Modèle | Caractéristiques techniques 


.6+| Gamme AFF A-Series | AFF A20 .6+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Fiche technique de la série AFF A"] 


| AFF A30 


| AFF A50 


| AFF A70 


| AFF A90 


| AFF A1K 


.3+| AFF série C | AFF C30 .3+| https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Fiche technique de la série AFF C"] 


| AFF C60 


| AFF C80 


.7+| ASA | ASA A20 .7+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Fiche technique ASA"] 


| ASA A30 


| ASA C30 


| ASA A50 


| ASA A70 


| ASA A90 


| ASA A1K 


.5+| FAS | FAS2750 .5+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Fiche technique FAS"] 


| FAS2820 


| FAS50 


| FAS70 


| FAS90 


.2+| AFX | AFX 1K .2+| https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["Fiche technique AFX"] 


| AFX 2K 
|===


[[cluster-interconnect-switch-options]]
== Options de commutateurs d'interconnexion de cluster

Le tableau suivant répertorie les commutateurs d’interconnexion de cluster Nexus disponibles pour les architectures FlexPod. FlexPod prend en charge tous les commutateurs de cluster pris en charge par ONTAP, y compris les commutateurs non Cisco, à condition qu’ils soient compatibles avec la version d’ONTAP déployée.

Pour obtenir la liste des commutateurs d'interconnexion de cluster compatibles, accédez à  https://hwu.netapp.com/["NetApp Hardware Universe"^], cliquez sur *Products > Networking > Switches*, puis sélectionnez *Cluster InterConnect Switch*. Vous pouvez filtrer par type de fournisseur, sélectionner un commutateur et cliquer sur *Show results* pour consulter des informations détaillées sur le commutateur.

Le tableau ci-dessous répertorie les commutateurs Cisco pouvant être utilisés comme commutateurs d'interconnexion de cluster.

|===
| Commutateur d'interconnexion de cluster | Caractéristiques techniques 


| Cisco Nexus 9336C-FX2 | https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html["Documentation NetApp : commutateurs Cisco Nexus 9336C-FX2"^] 
|===


[[netapp-disk-shelf-and-drive-options]]
== Options de tiroirs disques et de disques NetApp

Un minimum d’un tiroir disque NetApp est requis pour les contrôleurs de stockage qui ne possèdent pas de tiroir disque intégré. Le type de tiroir NetApp sélectionné détermine les types de disques disponibles dans ce tiroir.


NOTE: Pour connaître les références de tous les tiroirs disques et des disques, adressez-vous à votre ingénieur commercial.

Le tableau suivant répertorie les options de tiroir disque NetApp pour FlexPod Datacenter ainsi que des liens vers leurs spécifications techniques.

Pour obtenir la liste des disques pris en charge pour votre tiroir disque, allez à link:https://hwu.netapp.com/["NetApp Hardware Universe"^], sous *Products > Storage > Shelves* sélectionnez *ONTAP (AFF, ASA, FAS) or ONTAP (AFX)*, sélectionnez la version d'ONTAP que vous utilisez, puis sélectionnez le type de tiroir (exemple : *DS212C*) et cliquez sur *Show Results*. Cliquez sur *Supported Drives* pour voir les disques pris en charge pour des versions spécifiques d'ONTAP et les tiroirs disques.

|===
| Tiroir disque | Caractéristiques techniques 


| DS212C .6+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Tiroirs disques et supports de stockage"] 


| DS224C 


| DS460C 


| NS224 


| NS224 avec NSM100B 


| NX224 
|===


[[netapp-software-licensing-options]]
== Options NetApp de licences logicielles

Le tableau suivant répertorie les options de licence logicielle NetApp.

|===
| Licences logicielles NetApp | Caractéristiques techniques 


| ONTAP One pour AFF, FAS et AFX .2+| Contactez votre équipe commerciale NetApp pour en savoir plus sur les licences. 


| ONTAP One pour SAN pour ASA 
|===
Pour plus d'informations sur les licences logicielles NetApp, veuillez consulter le lien suivant : https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licences logicielles NetApp"^].



[[netapp-support-licensing-options]]
== Options de licence du support NetApp

SupportEdge Premium licences sont requises, et les références de ces licences varient en fonction des options sélectionnées dans la conception FlexPod Datacenter.

Le tableau suivant répertorie les options de licence de support NetApp pour les systèmes de stockage NetApp AFF, ASA, FAS et AFX.

|===
| Licences du support NetApp | Caractéristiques techniques 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===