---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_nexus_switching_modes_of_operation.html 
keywords: cisco, nexus, nx-os, aci, switching, modes, operation, datacenter, technical, specifications 
summary: Divers produits Cisco Nexus peuvent être utilisés comme composant de commutation d’un déploiement FlexPod donné. La plupart de ces options exploitent le logiciel Cisco NX-OS. La famille de commutateurs Cisco Nexus offre des fonctionnalités variées au sein de ses gammes de produits. Ces fonctionnalités sont détaillées plus loin dans ce document. 
---
= Modes de fonctionnement du commutateur Cisco Nexus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Divers produits Cisco Nexus peuvent être utilisés comme composant de commutation d’un déploiement FlexPod donné. La plupart de ces options exploitent le logiciel Cisco NX-OS. La famille de commutateurs Cisco Nexus offre des fonctionnalités variées au sein de ses gammes de produits. Ces fonctionnalités sont détaillées plus loin dans ce document.

L’offre de Cisco dans le domaine des réseaux définis par logiciel s’appelle Application Centric Infrastructure (ACI). La gamme de produits Cisco Nexus, qui prend en charge le mode ACI (mode fabric), peut également être déployée en mode NX-OS.

L'ACI Cisco est destinée aux déploiements de data Center axés sur les besoins d'une application spécifique. Les applications sont instanciées via une série de profils et de contrats permettant la connectivité de l'hôte ou de la machine virtuelle (VM) jusqu'au stockage.

FlexPod Datacenter est validé avec les deux modes de fonctionnement des commutateurs Cisco Nexus. Pour plus d'informations sur les modes ACI et NX-OS, consultez les pages Cisco suivantes :

* http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html["Application Centric Infrastructure (ACI) de Cisco"^]
* https://www.cisco.com/site/us/en/products/networking/cloud-networking/nx-os/index.html["Logiciel Cisco NX-OS"^]

