---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_solution_overview.html 
keywords: flexpod, datacenter, technical specifications, platform, architecture 
summary: 'La plateforme FlexPod est une architecture de centre de données prédéfinie et conforme à la bonne pratique, construite sur le Cisco Unified Computing System (Cisco UCS), la famille de commutateurs Cisco Nexus et les contrôleurs de stockage NetApp (NetApp AFF, ASA, FAS ou systèmes AFX).' 
---
= Caractéristiques techniques des data centers FlexPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La plateforme FlexPod est une architecture de centre de données prédéfinie et conforme à la bonne pratique, construite sur le Cisco Unified Computing System (Cisco UCS), la famille de commutateurs Cisco Nexus et MDS (pour FC), et les contrôleurs de stockage NetApp (systèmes AFF, ASA, FAS ou AFX).

FlexPod est une plateforme adaptée pour exécuter divers hyperviseurs de virtualisation, ainsi que des systèmes d'exploitation sans système d'exploitation et des charges de travail d'entreprise. FlexPod offre non seulement une configuration de base, mais également la possibilité d'être dimensionnée et optimisée afin de répondre à de nombreuses exigences et cas d'utilisation.


NOTE: Avant de commander une configuration complète FlexPod, veuillez consulter la page  http://www.netapp.com/us/technology/flexpod["NetApp FlexPod Page d'accueil"^] pour la dernière version de ces spécifications techniques.

link:dc-tech-spec_flexpod_platforms.html["Ensuite : plateformes FlexPod."]
