---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: flexpod, architecture, supported, validated, configurations, hardware, software 
summary: 'L"architecture FlexPod est définie par l"ensemble de règles décrites dans ce document.' 
---
= Prise en charge par rapport aux configurations FlexPod validées
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
L'architecture FlexPod est définie par l'ensemble de règles décrites dans ce document. Les composants matériels et les configurations logicielles doivent être pris en charge par le https://ucshcltool.cloudapps.cisco.com/public/["Liste de compatibilité matérielle et logicielle Cisco UCS"^] et le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp (IMT)"^].

Chaque conception validée par Cisco (CVD) ou architecture vérifiée NetApp (NVA) est une configuration FlexPod possible. Cisco et NetApp documentent ces combinaisons de configuration et les valident à l'aide de tests complets. Les déploiements FlexPod qui diffèrent de ces configurations sont entièrement pris en charge s'ils suivent les consignes décrites dans ce document et si tous les composants sont répertoriés comme compatibles dans la liste de compatibilité matérielle et logicielle Cisco UCS et avec NetApp http://mysupport.netapp.com/matrix["IMT"^].

Par exemple, l'ajout de contrôleurs de stockage ou de serveurs Cisco UCS et la mise à niveau du logiciel vers des versions plus récentes sont entièrement pris en charge si le logiciel, le matériel et les configurations sont conformes aux directives définies dans ce document.
