---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: 'Une configuration FlexPod Datacenter présente des exigences matérielles minimales, y compris, mais sans s"y limiter, les commutateurs, les interconnexions de fabric, les serveurs et les contrôleurs de stockage NetApp.' 
---
= Configuration matérielle minimale requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Une configuration FlexPod Datacenter présente des exigences matérielles minimales, y compris, mais sans s'y limiter, les commutateurs, les interconnexions de fabric, les serveurs et les contrôleurs de stockage NetApp.

Une configuration FlexPod présente la configuration matérielle minimale suivante :

* Deux commutateurs Cisco Nexus en configuration redondante. Cette configuration peut comprendre deux commutateurs redondants de la série Cisco Nexus 9000 mentionnée précédemment. Les deux commutateurs doivent être du même modèle et configurés dans le même mode de fonctionnement.



NOTE: Si vous déployez une architecture ACI, vous devez respecter les exigences supplémentaires suivantes : * Déployez les commutateurs Cisco Nexus 9000 Series selon une topologie leaf-spine. * Utilisez trois Cisco Application Policy Infrastructure Controllers (APIC).

* Deux interconnexions de structure Cisco UCS 6400, 6500 ou 6600 Series dans une configuration redondante, si vous utilisez les serveurs rack UCS C-Series ou les systèmes modulaires X-Series.
* Deux serveurs rack Cisco UCS série C avec connectivité FI et configuration gérée par Intersight (IMM), ou le Cisco UCS X-Series Direct avec Cisco IMM, ou le Cisco UCS X-Series Modular avec configuration gérée par Cisco Intersight (IMM).



NOTE: Si vous utilisez les serveurs rack UCS sans connectivité FI, vous pouvez utiliser CIMC ou le mode autonome Intersight pour la gestion.

* Deux contrôleurs NetApp AFF, NetApp ASA ou NetApp FAS configurés en paire haute disponibilité (HA) et déployés en cluster à deux nœuds. Si vous utilisez NetApp AFX, un minimum de quatre contrôleurs NetApp AFX est requis et doit être déployé en cluster HA à quatre nœuds, accompagné d'une paire de commutateurs d'interconnexion de cluster.
* Un minimum d’un tiroir disque NetApp est requis pour les contrôleurs de stockage qui ne possèdent pas de tiroir disque intégré.

