---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: 'Cette section décrit les exigences en matière d"alimentation électrique et les directives de câblage des tiroirs disques pour une conception FlexPod Datacenter.' 
---
= Directives relatives à l'alimentation électrique et au câblage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette section décrit les besoins en alimentation électrique et les directives de câblage pour une conception FlexPod Datacenter.



[[power-requirements]]
== Les besoins en alimentation électrique

Les exigences en termes d'alimentation pour le data Center FlexPod diffèrent selon l'emplacement où la configuration FlexPod Datacenter est installée.

Pour plus de données sur la puissance maximale requise et pour obtenir d'autres informations détaillées sur l'alimentation, consultez les spécifications techniques de chaque composant matériel répertorié dans la section link:dc-tech-spec_technical_specifications_and_references.html["Spécifications techniques et références : composants matériels"].

Pour obtenir des données détaillées sur la consommation électrique de Cisco UCS, consultez le https://ucspowercalculator.cisco.com/["Calculateur de puissance Cisco UCS"^].

Pour les données d'alimentation du contrôleur de stockage NetApp, consultez la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Sous *Plateformes*, sélectionnez la plateforme de stockage que vous souhaitez utiliser (par exemple, AFF A90), sélectionnez la version ONTAP, puis cliquez sur *Afficher les résultats*. Les données du cordon d'alimentation sont indiquées dans la section *Cordons d'alimentation compatibles*. Pour plus de détails sur les dimensions, le poids, la puissance, etc., reportez-vous à la section *Dimensions, poids, niveau sonore, alimentation*.



[[cabling-guidelines]]
== Directives de câblage

Cette section fournit des directives générales de câblage pour une conception FlexPod Datacenter.

* Assurez une connectivité redondante pour les connexions de calcul et de stockage.
* La vitesse des connexions doit être compatible avec les composants connectés.
* Consultez la section link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["Topologies FlexPod Datacenter"^] pour obtenir des instructions de câblage supplémentaires pour des topologies spécifiques.


Le tableau suivant fournit des recommandations de câblage pour les tiroirs disques NetApp pouvant être utilisés dans une conception FlexPod Datacenter.

|===


| Tiroir disque | Directives de câblage 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Règles de câblage SAS"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Exigences et bonnes pratiques relatives aux tiroirs disques NS224 et NX224"^] 


| NS224 avec NSM100B 


| NX224 
|===