---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: Les contrôleurs de stockage NetApp constituent la base du stockage dans l’architecture FlexPod Express, tant pour le démarrage que pour le stockage des données d’application. Cette section répertorie les différentes options de stockage NetApp dans l’architecture FlexPod Express. 
---
= Composants NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les contrôleurs de stockage NetApp constituent la base du stockage de l'architecture Express de FlexPod pour le stockage des données de démarrage et d'applications. Cette section répertorie les différentes options NetApp disponibles dans l'architecture FlexPod Express.



[[netapp-storage-controller-options]]
== Options de contrôleurs de stockage NetApp

Des contrôleurs redondants des séries AFF, ASA ou FAS sont requis dans l’architecture FlexPod Express. Les contrôleurs exécutent le logiciel ONTAP. Lors de la commande des contrôleurs de stockage, la version logicielle souhaitée peut être préinstallée sur les contrôleurs. Pour ONTAP, le cluster peut être déployé soit avec une paire de commutateurs d’interconnexion de cluster, soit dans une configuration de cluster sans commutateur.


NOTE: La configuration sans commutateur n'est prise en charge que pour une configuration à deux nœuds. Les commutateurs d'interconnexion de cluster sont nécessaires pour les configurations comportant plus de 4 nœuds et sont optionnels pour une configuration à deux nœuds.

Différentes options et configurations sont disponibles selon la plateforme de stockage choisie. Pour plus d'informations sur ces composants supplémentaires, veuillez contacter votre représentant commercial.

Les familles de contrôleurs répertoriées dans le tableau ci-dessous conviennent à une solution FlexPod car leur connexion aux commutateurs Cisco Nexus est transparente. Consultez la  http://hwu.netapp.com/["NetApp Hardware Universe"^] pour obtenir des informations de compatibilité spécifiques à chaque modèle de contrôleur.

|===
| NetApp entry-level storage Family pour FlexPod Express | Modèle | Caractéristiques techniques 


.2+| Gamme AFF A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentation AFF A-Series"] 


| A30 


| AFF série C | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentation AFF C-Series"] 


.2+| ASA série A | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentation ASA"] 


| A30 


| ASA série C | C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentation FAS"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== Tiroirs disques et disques NetApp

Un minimum d’un tiroir disque NetApp est requis pour les contrôleurs de stockage qui ne possèdent pas de tiroir disque intégré. Le type de tiroir NetApp sélectionné détermine les types de disques disponibles dans ce tiroir.


NOTE: Pour connaître les références de tous les tiroirs disques et des disques, adressez-vous à votre ingénieur commercial.

Le tableau suivant répertorie les options de tiroir disque NetApp pour FlexPod Express ainsi que des liens vers leurs spécifications techniques.

Pour obtenir la liste des disques compatibles avec votre tiroir disque, accédez à link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^], sous *Products > Storage > Shelves*, sélectionnez *ONTAP (AFF, ASA, FAS)*, sélectionnez la version d'ONTAP que vous utilisez, puis sélectionnez le type de tiroir (exemple : *DS212C*) et cliquez sur *Show Results*. Cliquez sur *Supported Drives* pour voir les disques pris en charge pour des versions spécifiques d'ONTAP et les tiroirs disques.

|===
| Tiroir disque | Caractéristiques techniques 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Tiroirs disques et supports de stockage"] 


| DS224C 


| DS460C 


| NS224 


| NS224 avec NSM100B 
|===


[[netapp-software-licensing-options]]
== Options NetApp de licences logicielles

Le tableau suivant répertorie les options de licence logicielle NetApp.

|===
| Licences logicielles NetApp | Caractéristiques techniques 


| ONTAP One pour AFF et FAS .2+| Contactez votre équipe commerciale NetApp pour en savoir plus sur les licences. 


| ONTAP One pour SAN pour ASA 
|===
Consultez ce lien pour plus d'informations sur les licences logicielles NetApp https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licences logicielles NetApp"^].



[[netapp-support-licensing-options]]
== Options de licence du support NetApp

Les licences SupportEdge Premium sont requises et les références associées à ces licences varient en fonction des options sélectionnées dans la conception FlexPod Express.

Le tableau suivant répertorie les options de licence de support NetApp pour les systèmes de stockage NetApp AFF, ASA et FAS.

|===
| Licences du support NetApp | Caractéristiques techniques 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===