---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_cisco_components.html 
keywords: cisco, components, server, options, rack, ucs, nexus, switches, x-series-direct, c-series 
summary: 'Cisco apporte une contribution substantielle à la conception et à l"architecture d"FlexPod Express. Il apporte les couches de calcul et de mise en réseau de la solution.' 
---
= Composants Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cisco apporte une contribution substantielle à la conception et à l'architecture d'FlexPod Express. Il apporte les couches de calcul et de mise en réseau de la solution. Cette section décrit les composants Cisco UCS et Cisco Nexus disponibles pour FlexPod Express.



== Options des serveurs lames Cisco UCS B-Series

Les lames Cisco UCS B-Series actuellement prises en charge dans la plateforme Cisco UCS Mini sont les B200 M5 et B420 M4. Les autres lames seront listées dans le tableau suivant au fur et à mesure qu'elles seront prises en charge dans la plateforme Cisco UCS Mini.

|===
| Serveur Cisco UCS B-Series | Numéro de référence | Caractéristiques techniques 


| CISCO UCS B200 M5 | UCSB-B200-M5 | https://www.cisco.com/c/en/us/support/servers-unified-computing/ucs-b200-m5-blade-server/model.html[] 


| CISCO UCS B200 M4 | UCSB-B200-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/b200m4-specsheet.pdf[] 


| CISCO UCS B420 M4 | UCSB-B420-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/b420m4-spec-sheet.pdf[] 
|===


== Options de serveurs en rack Cisco UCS C-Series

Les serveurs lames Cisco UCS série C sont disponibles en versions 1U et 2U, avec différentes options de processeur, de mémoire et d'E/S. Les références indiquées dans le tableau ci-dessous correspondent au serveur de base ; elles n'incluent pas les processeurs, la mémoire, les disques durs, les cartes PCIe ni le Cisco FEX. Plusieurs options de configuration sont disponibles et prises en charge dans FlexPod.

|===
| Serveur en rack Cisco UCS C-Series | Numéro de référence | Caractéristiques techniques 


| CISCO UCS C220 M4 | UCSC-C220-M4S | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c220m4-sff-spec-sheet.pdf[] 


| CISCO UCS C240 M4 | UCSC-C240-M4S | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c240m4-sff-spec-sheet.pdf[] 


| CISCO UCS C460 M4 | UCSC-C460-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c460m4_specsheet.pdf[] 
|===


== Commutateurs Cisco Nexus

Des commutateurs redondants sont nécessaires pour toutes les architectures FlexPod Express.

L’architecture FlexPod Express avec NetApp AFF ou FAS est basée sur le commutateur Cisco Nexus 31108. FlexPod Express avec l’architecture Cisco UCS Mini (gérée par Cisco UCS) est validée à l’aide du commutateur Cisco Nexus 3524. Cette configuration peut également être déployée avec un commutateur standard.

Le FlexPod Express avec système de stockage E-Series peut être déployé avec un commutateur standard.

Le tableau suivant répertorie les références des châssis de la série Cisco Nexus ; elles n’incluent pas les modules SFP ou les modules complémentaires.

|===
| Commutateur Cisco Nexus Series | Numéro de référence | Caractéristiques techniques 


| Commutateurs Cisco Nexus 3048 | N3K-C3048TP-1GE | http://www.cisco.com/c/en/us/products/collateral/switches/nexus-3000-series-switches/data_sheet_c78-685363.html[] 


| Commutateurs Cisco Nexus 31108 | N3K-C31108PC-V | http://www.cisco.com/c/en/us/products/switches/nexus-31108pc-v-switch/index.html[] 


| Commutateurs Cisco Nexus 9396 | N9K-C9396PX | http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729405.html[] 


| Cisco Nexus 3172 | N3K-C3172 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-3000-series-switches/data_sheet_c78-729483.html[] 
|===


== Options de licence du support Cisco

Des contrats de support SMARTnet valides sont requis pour tous les équipements Cisco dans l’architecture FlexPod Express.


NOTE: Les licences requises et les numéros de référence de ces licences doivent être vérifiés par votre représentant commercial, car ils peuvent différer selon les produits.

Le tableau suivant répertorie les options de licence de prise en charge de Cisco.

|===
| Licences du support Cisco | Guide de licence 


| SMARTnet 24x7x4 | http://www.cisco.com/web/services/portfolio/product-technical-support/smartnet/index.html[] 
|===