---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_software_requirements.html 
keywords: minimum, software, requirements, flexpod, express, aff, fas, e, series 
summary: Cette section décrit la configuration logicielle minimale requise pour les différentes versions de FlexPod Express. 
---
= Configuration logicielle minimale requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit la configuration logicielle minimale requise pour les différentes versions de FlexPod Express.



== Configuration logicielle requise pour FlexPod Express avec NetApp AFF/ ASA/ FAS

Les exigences logicielles pour le FlexPod Express avec NetApp AFF/ ASA/ FAS incluent :

* ONTAP 9.16 ou version ultérieure
* Cisco NX-OS version 10.4(6)M ou ultérieure



NOTE: Toutes les versions logicielles listées dans cette section constituent les exigences minimales pour les composants matériels (NetApp et Cisco) listés dans les sections suivantes du document.

Tous les logiciels doivent être répertoriés et pris en charge dans le http://support.netapp.com/matrix/["NetApp IMT"^]. Certaines fonctionnalités logicielles peuvent nécessiter des versions de code plus récentes que les valeurs minimales répertoriées dans les architectures précédentes.
