---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: Cette section décrit les conditions de connectivité requises pour les différentes versions de FlexPod Express. 
---
= Les besoins en connectivité
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les exigences générales de connectivité pour les différentes versions de FlexPod Express.



[[connectivity-requirements-for-flexpod-express-with-netapp-aff-asa-fas]]
== Exigences de connectivité pour FlexPod Express avec NetApp AFF/ ASA/ FAS

Les exigences de connectivité pour FlexPod Express avec NetApp AFF/ ASA/ FAS comprennent généralement :

* NetApp Les contrôleurs de stockage doivent être directement connectés aux commutateurs Cisco Nexus.
* Pour les déploiements Cisco UCS X-Series Direct, les contrôleurs de stockage NetApp peuvent être connectés directement aux Fabric Interconnects intégrés.
* Aucun équipement supplémentaire ne peut être placé en ligne entre les composants principaux de FlexPod.
* Des canaux de ports virtuels (vPC) sont nécessaires pour connecter les commutateurs Cisco Nexus série 9000 aux contrôleurs de stockage NetApp.
* Bien qu'elle ne soit pas requise, l'activation de la prise en charge des trames Jumbo est recommandée dans l'ensemble de l'environnement.


Reportez-vous à la section link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["Topologies FlexPod Express"^] relative aux exigences de connectivité spécifiques à chaque topologie.
