---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, aff, asa, fas, cimc, configuration, rack, servers, ucs 
summary: Cette section décrit la configuration matérielle minimale requise pour les différentes versions de FlexPod Express. 
---
= Configuration matérielle minimale requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit la configuration matérielle minimale requise pour les différentes versions de FlexPod Express.



[[flexpod-express-with-netapp-aff-asa-fas]]
== FlexPod Express avec NetApp AFF/ ASA/ FAS

Les exigences matérielles pour les solutions FlexPod Express qui utilisent des contrôleurs NetApp AFF, ASA ou FAS pour le stockage sous-jacent comprennent les configurations décrites dans cette section.

La configuration matérielle minimale requise pour FlexPod Express est indiquée ci-dessous :

* Deux commutateurs Ethernet standard 10 Gbit/s en configuration redondante (Cisco Nexus 9200 et 9300)
* Serveurs rack autonomes Cisco UCS C-Series avec configuration de serveur rack autonome basée sur CIMC ou configuration autonome Intersight, ou Cisco UCS X-Series Direct avec configuration gérée par Cisco Intersight (IMM).
* Deux contrôleurs d'entrée de gamme NetApp AFF (A20, A30 ou C30), NetApp ASA (A20, A30 ou C30) ou NetApp FAS (2750, 2820 ou FAS 50) en configuration de paire à haute disponibilité (HA) déployés en cluster à deux nœuds

