---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: 'Cette section décrit les exigences en matière d"alimentation et les directives de câblage des tiroirs disques pour une conception FlexPod Express.' 
---
= Directives relatives à l'alimentation électrique et au câblage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les exigences en matière d'alimentation et les directives de câblage pour une conception FlexPod Express.



[[power-requirements]]
== Les besoins en alimentation électrique

Les besoins en alimentation pour FlexPod Express varient en fonction de l'emplacement où la configuration FlexPod Express est installée.

Pour plus de données sur la puissance maximale requise et pour d'autres informations détaillées sur la consommation d'énergie, consultez la link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["spécifications techniques"^] pour chaque composant matériel.

Pour en savoir plus sur les données de puissance Cisco UCS, consultez le http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Calculateur de puissance Cisco UCS"^].

Pour les données d'alimentation du contrôleur de stockage NetApp, consultez la  http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe"^]. Sous *Plateformes*, sélectionnez la plateforme de stockage que vous souhaitez utiliser (par exemple, AFF A20), sélectionnez la version ONTAP, puis cliquez sur *Afficher les résultats*. Les données relatives au cordon d'alimentation figurent dans la section *Cordons d'alimentation compatibles* et, pour plus de détails sur les dimensions, le poids, la puissance, etc., reportez-vous à la section *Dimensions, poids, niveau sonore et alimentation*.



[[cabling-guidelines]]
== Directives de câblage

Cette section fournit des directives générales de câblage pour une conception FlexPod Express.

* Assurez une connectivité redondante pour les connexions de calcul et de stockage.
* La vitesse des connexions doit être compatible avec les composants connectés.
* Consultez la section link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["Topologies FlexPod Express"^] pour obtenir des instructions de câblage supplémentaires pour des topologies spécifiques.


Le tableau suivant fournit des instructions de câblage pour les tiroirs disques NetApp pouvant être utilisés dans une conception FlexPod Express.

|===


| Tiroir disque | Directives de câblage 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Règles de câblage SAS"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Exigences et bonnes pratiques relatives au tiroir NS224"^] 


| NS224 avec NSM100B 
|===