---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: Les contrôleurs de stockage NetApp constituent la base du stockage dans l’architecture FlexPod Express, tant pour le démarrage que pour le stockage des données d’application. Cette section répertorie les différentes options de stockage NetApp dans l’architecture FlexPod Express. 
---
= Composants NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Les contrôleurs de stockage NetApp constituent la base du stockage de l'architecture Express de FlexPod pour le stockage des données de démarrage et d'applications. Cette section répertorie les différentes options NetApp disponibles dans l'architecture FlexPod Express.



== Options de contrôleurs de stockage NetApp

Des contrôleurs redondants des séries AFF, ASA ou FAS sont requis dans l’architecture FlexPod Express. Les contrôleurs exécutent le logiciel ONTAP. Lors de la commande des contrôleurs de stockage, la version logicielle souhaitée peut être préchargée sur les contrôleurs. Pour ONTAP, le cluster peut être déployé soit avec une paire de commutateurs d’interconnexion de cluster, soit dans une configuration de cluster sans commutateur.


NOTE: La configuration sans commutateur n'est prise en charge que pour une configuration à deux nœuds. Les commutateurs d'interconnexion de cluster sont nécessaires pour les configurations comportant plus de 4 nœuds et sont optionnels pour une configuration à deux nœuds.

Différentes options et configurations sont disponibles selon la plateforme de stockage choisie. Consultez votre représentant commercial pour plus de détails sur ces composants supplémentaires.

Les familles de contrôleurs répertoriées dans le tableau ci-dessous conviennent à une solution FlexPod car leur connexion aux commutateurs Cisco Nexus est transparente. Consultez la  http://hwu.netapp.com/["NetApp Hardware Universe"^] pour obtenir des informations de compatibilité spécifiques à chaque modèle de contrôleur.

|===
| NetApp entry-level storage Family pour FlexPod Express | Modèle | Caractéristiques techniques 


.2+| Gamme AFF A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentation AFF A-Series"] 


| A30 


| AFF série C | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentation AFF C-Series"] 


.2+| ASA série A | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentation ASA A-Series"] 


| A30 


| ASA série C | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentation ASA C-Series"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentation FAS"] 


| FAS 2820 
|===


== Tiroirs disques et disques NetApp

Un minimum d’un NetApp tiroir disque est requis pour les contrôleurs de stockage.

Le type de tiroir NetApp sélectionné détermine les types de disques disponibles dans ce tiroir.


NOTE: Pour connaître les références de tous les tiroirs disques et des disques, adressez-vous à votre ingénieur commercial.

Pour plus d'informations sur les disques pris en charge, cliquez sur le lien NetApp Hardware Universe dans le tableau suivant, puis sélectionnez disques pris en charge.

Le tableau suivant répertorie les options de tiroirs disques NetApp, ainsi que les disques pris en charge pour chaque type de tiroir, disponibles sur NetApp Hardware Universe. Suivez le lien Hardware Universe, sélectionnez la version du ONTAP que vous utilisez, puis sélectionnez le type de tiroir. Sous l'image de tiroir, cliquez sur disques pris en charge pour afficher les disques pris en charge pour des versions spécifiques de ONTAP et des tiroirs disques.

|===
| Tiroir disque | Caractéristiques techniques 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["Tiroirs disques et supports de stockage disques pris en charge sur NetApp Hardware Universe"] 


| DS224C 


| DS460C 


| NS224 


| NS224 avec NSM100B 
|===


== Options NetApp de licences logicielles

Le tableau suivant répertorie les options de licence logicielle NetApp.

|===
| Licences logicielles NetApp | Caractéristiques techniques 


| ONTAP One ou ONTAP base pour AFF et FAS .2+| Contactez votre équipe commerciale NetApp pour en savoir plus sur les licences. 


| ONTAP One pour SAN pour ASA 
|===


== Options de licence du support NetApp

Les licences SupportEdge Premium sont requises et les références associées à ces licences varient en fonction des options sélectionnées dans la conception FlexPod Express.

Le tableau suivant répertorie les options de licence de support NetApp pour les systèmes de stockage NetApp AFF, ASA et FAS.

|===
| Licences du support NetApp | Numéro de référence | Caractéristiques techniques 


| SupportEdge Premium4 heures sur place ; mois : 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===