---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html 
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers 
summary: Cette section décrit les spécifications techniques importantes de chaque composant de FlexPod Express. 
---
= Spécifications techniques et références
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les spécifications techniques importantes de chaque composant de FlexPod Express.



[[cisco-ucs-x-series-direct-chassis]]
== Châssis Cisco UCS X-Series Direct

Les spécifications techniques du châssis Cisco UCS X-Series Direct, telles qu'indiquées dans le tableau ci-dessous, comprennent les composants suivants :

* Nombre d'unités de rack
* Nombre maximal de nœuds
* Fonctionnalité de structure unifiée
* Nombre de baies d'E/S pour IFMS


|===
| Composant | châssis Cisco UCS X9508 


| Unités en rack | 7 


| Nombre maximal de nœuds | 8 


| Capacité de la structure unifiée | Oui. 


| Baies d'E/S pour IFMS | Deux baies pour les modules de structure intelligente Cisco UCS 9108 (IFMS) 
|===
Pour plus d'informations, reportez-vous à la section link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Fiche technique sur le châssis Cisco UCS X9508 X-Series"^].



[[cisco-ucs-x-series-direct-compute-node]]
== Nœud de calcul direct Cisco UCS X-Series

Les spécifications techniques du nœud de calcul Cisco UCS X-Series comprennent les composants suivants :

* Nombre de sockets du processeur
* Prise en charge du processeur
* Capacité de la mémoire
* Dimensionnement et vitesse
* Prise en charge du démarrage SAN
* Nombre de logements d'adaptateur mezzanine
* Débit d'E/S maximal
* Format
* Nombre maximal de nœuds de calcul par châssis


Consultez le tableau ci-dessous pour connaître les spécifications techniques des nœuds de calcul directs Cisco UCS X-Series.

|===


| Composant | Fiche technique Cisco UCS 


| Cisco UCS X210c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Cisco UCS X210c M7 Nœud de calcul"] 


| Cisco UCS X210c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Cisco UCS X210c M8 Nœud de calcul"] 


| Cisco UCS X215c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Cisco UCS X215c M8 Nœud de calcul"] 


| Cisco UCS X410c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Cisco UCS X410c M7 Nœud de calcul"] 


| Cisco UCS X410c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Cisco UCS X410c M8 Nœud de calcul"] 
|===


[[cisco-ucs-x-series-direct-fabric-interconnect]]
== Cisco UCS X-Series Interconnexion directe de la structure

Les spécifications techniques de l'interconnexion directe Cisco UCS X-Series incluent le format, le nombre total de ports et d'emplacements d'extension, ainsi que la capacité de débit. Consultez le tableau ci-dessous pour la fiche technique de l'interconnexion directe Cisco UCS X-Series.

|===
| Composant | Fiche technique Cisco UCS 


| Interconnexion de fabric Cisco UCS 9108 100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Interconnexion de fabric Cisco UCS 9108 100G"] 
|===


[[cisco-ucs-xe9305-chassis-cisco-unified-edge]]
== Châssis Cisco UCS XE9305 (Cisco Unified Edge)

Les spécifications techniques du châssis Cisco UCS XE9305, comme indiqué dans le tableau ci-dessous, incluent les composants suivants :

|===
| Composant | châssis Cisco UCS XE9305 


| Unités en rack | 3 


| Nombre maximal de nœuds | 5 nœuds de calcul Cisco UCS XE130c M8 ou 2 nœuds de calcul Cisco UCS XE150c M8 
|===
Pour plus d'informations, consultez le link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf["Fiche technique du châssis Cisco UCS XE9305"^].



[[cisco-ucs-compute-nodes-for-cisco-unified-edge]]
== Nœuds de calcul Cisco UCS pour Cisco Unified Edge

Les spécifications techniques des nœuds de calcul Cisco UCS pour Cisco Unified Edge comprennent les composants suivants :

* Nombre de sockets du processeur
* Prise en charge du processeur
* Prise en charge GPU
* Capacité de la mémoire
* Dimensionnement et vitesse
* Débit d'E/S maximal
* Format


Les nœuds de calcul prennent également en charge les GPU, le XE130c M8 prend en charge le GPU NVIDIA L4 et le XE150c M8 prend en charge les GPU NVIDIA RTX PRO 4500 / 6000 Blackwell Server Edition. Consultez le tableau ci-dessous pour les spécifications techniques des nœuds de calcul Cisco UCS Unified Edge.

|===


| Composant | Fiche technique Cisco UCS 


| Cisco UCS XE130c M8 Nœud de calcul | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdf["Cisco UCS XE130c M8 Nœud de calcul"] 


| Cisco UCS XE150c M8 Nœud de calcul | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/unified-edge/cisco-ucs-xe150c-m8-compute-node.pdf["Cisco UCS XE150c M8 Nœud de calcul"] 
|===
Veuillez vous référer à link:https://www.cisco.com/c/en/us/products/servers-unified-computing/unified-edge/datasheet-listing.html["Liste des fiches techniques Cisco Unified Edge"^] pour plus de détails.



[[cisco-ucs-c-series-rack-servers]]
== Serveurs en rack Cisco UCS C-Series

Les spécifications techniques des serveurs rack Cisco UCS série C comprennent la prise en charge des processeurs, la capacité mémoire maximale, le nombre d'emplacements PCIe et le format. Pour plus de détails sur les modèles de serveurs UCS compatibles, consultez la  https://ucshcltool.cloudapps.cisco.com/public/["Compatibilité matérielle Cisco"^] liste.

Consultez le tableau ci-dessous pour connaître les spécifications techniques des serveurs rack Cisco UCS série C.

|===
| Composant | Fiche technique Cisco UCS 


| Cisco UCS C220 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Serveur en rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Serveur en rack Cisco UCS C220 M8"] 


| CISCO UCS C225 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html["Serveur rack Cisco UCS C225 M6"] 


| Cisco UCS C240 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Serveur en rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Serveur en rack Cisco UCS C240 M8"] 


| CISCO UCS C245 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html["Serveur rack Cisco UCS C245 M6"] 


| Cisco UCS C245 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Serveur en rack Cisco UCS C245 M8"] 
|===


[[cisco-nexus-switches]]
== Commutateurs Cisco Nexus

Les spécifications techniques des commutateurs Cisco Nexus sont détaillées dans la fiche technique de chaque modèle. Les spécifications comprennent la taille du format, le nombre de superviseurs, de modules de fabric et d'emplacements pour cartes d'interface, ainsi que le nombre maximal de ports. Ces fiches techniques se trouvent dans le tableau suivant.

|===
| Composant | Fiche technique Cisco Nexus 


| Cisco Nexus 9200 Series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Commutateurs Cisco Nexus 9200 Series"] 


| Cisco Nexus 9300 Series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Commutateurs Cisco Nexus 9300 Series"] 
|===


[[netapp-storage-controllers]]
== Contrôleurs de stockage NetApp

Les spécifications techniques des contrôleurs de stockage NetApp comprennent la configuration de la plateforme, la capacité brute maximale, la mémoire, le facteur de forme, les exigences de version ONTAP, les tiroirs disques, etc.



[[netapp-aff-a-series]]
=== NetApp AFF A-Series

Les contrôleurs de stockage NetApp AFF série A d'entrée de gamme sont pris en charge pour une utilisation dans FlexPod Express. Des informations supplémentaires sont disponibles dans la  https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Spécifications techniques de la série AFF A"^] fiche technique et dans la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consultez la documentation spécifique à la plateforme indiquée dans le tableau ci-dessous pour obtenir des informations détaillées sur un modèle AFF particulier.

|===
| Composant | Documentation sur la plateforme du contrôleur AFF A-Series 


| NetApp AFF A20 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance["Caractéristiques principales de l'AFF A20"] 


| NetApp AFF A30 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance["Caractéristiques principales de l'AFF A30"] 
|===


[[netapp-aff-c-series]]
=== NetApp AFF C-Series

Les contrôleurs de stockage NetApp AFF C-Series d'entrée de gamme sont pris en charge pour une utilisation dans FlexPod Express. Des informations supplémentaires sont disponibles dans la  https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Spécifications techniques de la série AFF C"^] fiche technique et dans la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consultez la documentation spécifique à la plateforme indiquée dans le tableau ci-dessous pour obtenir des informations détaillées sur un modèle AFF particulier.

|===
| Composant | Documentation de la plateforme de contrôleurs AFF C-Series 


| NetApp AFF C30 | https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html["Caractéristiques principales de l'AFF C30"] 
|===


[[netapp-asa-a-series]]
=== NetApp ASA A-Series

Les modèles d'entrée de gamme des contrôleurs de stockage NetApp ASA série A sont pris en charge pour une utilisation dans FlexPod Express. Des informations supplémentaires sont disponibles dans la  https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA Spécifications techniques de la série A"^] fiche technique et dans la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consultez la documentation spécifique à la plateforme répertoriée dans le tableau suivant pour obtenir des informations détaillées sur un modèle ASA particulier.

|===
| Composant | NetApp Documentation de la plateforme de contrôleurs ASA A-Series 


| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html["Caractéristiques principales de l'ASA A20"] 


| NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html["Caractéristiques principales de l'ASA A30"] 
|===


[[netapp-asa-c-series]]
=== NetApp ASA C-Series

Les modèles d'entrée de gamme des contrôleurs de stockage NetApp ASA série C sont pris en charge pour une utilisation dans FlexPod Express. Des informations supplémentaires sont disponibles dans la  https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA Spécifications techniques de la série C"^] fiche technique et dans la  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consultez la documentation spécifique à la plateforme répertoriée dans le tableau suivant pour obtenir des informations détaillées sur un modèle ASA particulier.

|===
| Composant | NetApp Documentation de la plateforme de contrôleurs ASA C-Series 


| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Caractéristiques principales de l'ASA C30"] 
|===


[[netapp-fas-series]]
=== NetApp Série FAS

Les contrôleurs de stockage FAS d'entrée de gamme sont pris en charge pour une utilisation dans un FlexPod Express. Les spécifications détaillées de tous les contrôleurs de stockage de la série FAS sont disponibles dans la https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consultez la documentation spécifique à la plateforme indiquée dans le tableau ci-dessous pour des informations détaillées sur un modèle FAS particulier.

|===
| Composant | Documentation sur la plateforme des contrôleurs de la gamme FAS 


| Série FAS2750 | https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html["FAS2750 Spécifications clés"^] 


| Série FAS2820 | https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html["Spécifications clés du FAS2820"^] 


| Série FAS50 | https://docs.netapp.com/us-en/ontap-systems/fas50/overview.html["Spécifications clés du FAS50"^] 
|===


[[netapp-disk-shelves]]
=== Tiroirs disques NetApp

Les spécifications techniques des baies de disques NetApp comprennent le format, le nombre de disques par baie et les modules d'E/S ; cette documentation est disponible dans le tableau suivant. Pour plus d'informations, veuillez consulter la  https://hwu.netapp.com/["NetApp Hardware Universe"^].

|===
| Composant | Documentation du tiroir disque FAS/AFF NetApp 


| Tiroir disque NetApp DS212C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentation des tiroirs disques DS212C"] 


| Tiroir disque NetApp DS224C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentation du tiroir disque DS224C"] 


| Tiroir disque DS460C NetApp | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentation des tiroirs disques DS460C"] 


| NetApp NS224 Étagère à disques | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentation du tiroir disque NS224"] 


| NS224 avec étagère à disques NSM 100B | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentation du shelf de disques NS224 avec NSM 100B"] 
|===


[[netapp-drives]]
=== Disques NetApp

Les spécifications techniques des disques NetApp incluent la taille, la capacité du disque, les tours/min des disques, les contrôleurs et les exigences de version ONTAP. Ces spécifications sont disponibles dans la section entraînements du http://hwu.netapp.com/Drives/Index?queryId=1581392["NetApp Hardware Universe"^].
