---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_storage_software.html 
keywords: storage, software, flexpod, express, ontap, e, series, santricity 
summary: 'Les systèmes d"exploitation de stockage répertoriés dans cette section sont pris en charge par la plateforme FlexPod Express.' 
---
= Logiciel de stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod Express prend en charge les systèmes de stockage qui exécutent les systèmes d'exploitation NetApp ONTAP ou SANtricity.



== NetApp ONTAP

Le logiciel NetApp ONTAP est le système d'exploitation qui fonctionne sur les systèmes de stockage AFF et FAS. ONTAP offre une architecture de stockage hautement évolutive qui permet des opérations sans interruption, des mises à niveau sans interruption et une infrastructure de données agile.

Pour plus d'informations sur ONTAP, consultez le http://www.netapp.com/us/products/platform-os/ontap/index.aspx["Page produit ONTAP"^].



== Logiciel SANtricity E-Series

Le logiciel SANtricity est le système d'exploitation qui s'exécute sur les systèmes de stockage E-Series. SANtricity offre un système très flexible qui répond à divers besoins applicatifs et propose une haute disponibilité intégrée ainsi qu'un large éventail de fonctionnalités de protection des données.

Pour plus d'informations, consultez le  http://www.netapp.com/us/products/platform-os/santricity/index.aspx["Page produit SANtricity"^].
