---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs 
summary: 'FlexPod Express est une architecture de bonne pratique prédéfinie, construite sur le Cisco Unified Computing System (Cisco UCS) et la famille de commutateurs Cisco Nexus, et la couche de stockage est construite à l"aide du NetApp FAS ou du NetApp système de stockage E-Series.' 
---
= TR-4293 : FlexPod Express Spécifications techniques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthick Radhakrishnan, Arvind Ramakrishnan, Lindsey Street, Savita Kumari, NetApp

[role="lead"]
FlexPod Express est une architecture de bonne pratique prédéfinie, construite sur le Cisco Unified Computing System (Cisco UCS) et la famille de commutateurs Cisco Nexus, et la couche de stockage est construite en utilisant les NetApp FAS ou le NetApp système de stockage E-Series. FlexPod Express constitue une plateforme adaptée à l'exécution de divers hyperviseurs de virtualisation, de systèmes d'exploitation physiques (bare metal) et de charges de travail d'entreprise.

FlexPod Express offre non seulement une configuration de base, mais aussi la flexibilité nécessaire pour être dimensionnée et optimisée afin de répondre à de nombreux cas d'utilisation et exigences différents. Ce document catégorise les configurations FlexPod Express en fonction du système de stockage utilisé, FlexPod Express avec NetApp FAS et FlexPod Express avec E-Series.
