---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: Cette section décrit les conditions de connectivité requises pour les différentes versions de FlexPod Express. 
---
= Les besoins en connectivité
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section décrit les conditions de connectivité requises pour les différentes versions de FlexPod Express.



== Exigences de connectivité pour FlexPod Express avec NetApp AFF/ ASA/ FAS

Les exigences de connectivité pour FlexPod Express avec NetApp AFF/ ASA/ FAS comprennent :

* NetApp Les contrôleurs de stockage doivent être directement connectés aux commutateurs Cisco Nexus.
* Pour les déploiements UCS X-series Direct, les contrôleurs de stockage NetApp peuvent être connectés directement aux Fabric Interconnects intégrés.
* Aucun équipement supplémentaire ne peut être placé en ligne entre les composants principaux de FlexPod.
* Des canaux de ports virtuels (vPC) sont nécessaires pour connecter les commutateurs Cisco Nexus série 9000 aux contrôleurs de stockage NetApp.
* Bien qu'elle ne soit pas requise, l'activation de la prise en charge des trames Jumbo est recommandée dans l'ensemble de l'environnement.

