---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_introduction.html 
keywords: flexpod, fabricpool, inactive, data, tiering, amazon, aws, s3 
summary: 'Dans ce rapport technique, nous passons en revue la fonctionnalité de Tiering des données de FabricPool ONTAP dans le cadre d"une architecture d"infrastructure convergée FlexPod de NetApp et Cisco.' 
---
= Tr-4801 : FlexPod avec FabricPool - Tiering des données inactives vers Amazon AWS S3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Scott Kovacs, NetApp

[role="lead"]
Les prix du stockage Flash continuent de baisser, ce qui est désormais disponible pour les charges de travail et les applications qui n'étaient pas considérées comme des candidats auparavant pour le stockage Flash. Toutefois, l'utilisation la plus efficace de l'investissement de stockage est encore cruciale pour les responsables INFORMATIQUES. Le service IT reste contraintes de fournir des services plus performants avec peu ou pas d'augmentation budgétaire. En réponse à ces besoins, NetApp FabricPool vous permet d'exploiter les économies du cloud en transférant les données peu utilisées hors de votre stockage Flash sur site, cher, vers un Tier de stockage plus économique dans le cloud public. Le transfert des données peu utilisées vers le cloud libère un espace de stockage Flash précieux sur les systèmes AFF ou FAS, ce qui permet d'obtenir davantage de capacité pour les workloads stratégiques vers le Tier Flash haute performance.

Dans ce rapport technique, nous passons en revue la fonctionnalité de Tiering des données FabricPool de NetApp ONTAP dans le cadre d'une architecture d'infrastructure convergée FlexPod de NetApp et Cisco. Vous devez maîtriser l'architecture d'infrastructure convergée FlexPod Datacenter et le logiciel de stockage ONTAP pour exploiter pleinement les concepts abordés dans ce rapport technique. Connaissant bien FlexPod et ONTAP, nous présentons le FabricPool, son fonctionnement et la façon dont il peut être utilisé pour une utilisation plus efficace du stockage Flash sur site. Une grande partie du contenu de ce rapport est abordée de manière plus détaillée dans le https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["Tr-4598 meilleures pratiques de FabricPool"^] Et documentation des produits ONTAP. Le contenu a été condensé pour une infrastructure FlexPod et ne couvre pas tous les cas d'utilisation de FabricPool. Toutes les fonctionnalités et concepts abordés sont disponibles dans ONTAP 9.6.

Pour plus d'informations sur FlexPod, consultez le https://www.netapp.com/pdf.html?item=/media/12424-tr4036.pdf["Tr-4036 spécifications techniques du data Center FlexPod"^].
