---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Où trouver des informations complémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-conclusion.html["Précédent: Conclusion."]

[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Page d'accueil de FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guides de conception et de déploiement validés par Cisco pour FlexPod
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* NetApp BlueXP
+
https://bluexp.netapp.com/["https://bluexp.netapp.com/"^]

* NetApp Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html"^]

* Démarrage rapide de Cloud Volumes ONTAP dans AWS
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html"^]

* Réplication SnapMirror
+
https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication.html["https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication.html"^]

* Tr-3928 : meilleures pratiques NetApp pour Epic
+
https://www.netapp.com/pdf.html?item=/media/17137-tr3928pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17137-tr3928pdf.pdf"^]

* Tr-4693 : Guide de déploiement du data Center FlexPod pour les DME EPIC
+
https://www.netapp.com/media/10658-tr-4693.pdf["https://www.netapp.com/media/10658-tr-4693.pdf"^]

* FlexPod pour Epic
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmw_epic.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmw_epic.html"^]

* Matrice d'interopérabilité NetApp
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]

* Outil d'interopérabilité matérielle et logicielle Cisco UCS
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Guide de compatibilité VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





=== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Mars 2023 | Version initiale 
|===