---
sidebar: sidebar 
permalink: hybrid-cloud/flexpod-rho-cvo-conclusion.html 
keywords: conclusion 
summary: 'Avec cette solution, nous avons mis en œuvre un plan de protection pour les applications conteneurisées qui sont exécutées sur FlexPod et AWS à l"aide du portefeuille NetApp Astra. NetApp Astra Control Center et Astra Trident, ainsi que Cloud Volumes ONTAP, Red Hat OpenShift et l"infrastructure FlexPod, ont constitué les principaux composants de cette solution.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-rho-cvo-application-recovery-with-remote-backups.html["Précédente : restauration d'applications avec sauvegardes distantes."]

[role="lead"]
Avec cette solution, nous avons mis en œuvre un plan de protection pour les applications conteneurisées qui sont exécutées sur FlexPod et AWS à l'aide du portefeuille NetApp Astra. NetApp Astra Control Center et Astra Trident, ainsi que Cloud Volumes ONTAP, Red Hat OpenShift et l'infrastructure FlexPod, ont constitué les principaux composants de cette solution.

Nous avons démontré la protection des applications en capturant des snapshots et en exécutant des sauvegardes complètes afin de restaurer les applications sur différents clusters K8s exécutés sur les environnements cloud et sur site.

Nous avons également démontré le clonage des applications sur les clusters K8s, afin de permettre aux clients de migrer leurs applications vers les clusters K8s de leur choix.

FlexPod a constamment évolué pour permettre à ses clients de moderniser leurs applications et leurs processus de fourniture d'informations. Avec cette solution, les clients de FlexPod peuvent créer en toute confiance leur plan de reprise après incident BCDR pour leurs applications cloud natives, en utilisant le cloud public comme emplacement dans le cadre d'un plan de reprise après incident transitoire ou à temps complet, tout en conservant le coût de la solution le plus bas.

Astra Control vous permet de déplacer une application avec ses données d'un cluster Kubernetes vers un autre, quel que soit l'emplacement des clusters. Elle accélère également le déploiement, les opérations et la protection de vos applications cloud.



== Dépannage

Pour obtenir des conseils de dépannage, reportez-vous à la section https://docs.netapp.com/us-en/astra-control-center/support/troubleshooting-acc.html["documentation en ligne"^].



== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Page d'accueil de FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guides de conception et de déploiement validés par Cisco pour FlexPod
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* Déploiement de FlexPod avec Infrastructure as code pour VMware avec Ansible
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html#AnsibleAutomationWorkflowandSolutionDeployment"^]

* Déploiement de FlexPod avec Infrastructure as code pour Red Hat OpenShift bare Metal avec Ansible
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_iac_redhat_openshift.html"^]

* Outil d'interopérabilité matérielle et logicielle Cisco UCS
+
https://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Fiche technique Cisco Intersight
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* Documentation NetApp Astra
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra Control Center
+
https://docs.netapp.com/us-en/astra-control-center/index.html["https://docs.netapp.com/us-en/astra-control-center/index.html"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/trident/index.html["https://docs.netapp.com/us-en/trident/index.html"^]

* NetApp Cloud Manager
+
https://docs.netapp.com/us-en/occm/concept_overview.html["https://docs.netapp.com/us-en/occm/concept_overview.html"^]

* NetApp Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/occm/task_getting_started_aws.html["https://docs.netapp.com/us-en/occm/task_getting_started_aws.html"^]

* Red Hat OpenShift
+
https://www.openshift.com/["https://www.openshift.com/"^]

* Matrice d'interopérabilité NetApp
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Juillet 2022 | Lancement de l'ACC 22.04.0. 
|===