---
sidebar: sidebar 
permalink: hybrid-cloud/gcp-ncvo-conclusion.html 
keywords: conclusion 
summary: 'Dans cette solution, le service de données cloud NetApp, Cloud Volumes ONTAP et l"infrastructure de data Center FlexPod ont été utilisés pour créer une solution de reprise après incident avec un cloud public optimisé par Cisco Intersight Cloud Orchestrator. La solution FlexPod a constamment évolué pour permettre aux clients de moderniser leurs applications et leurs processus de distribution. Avec cette solution, vous pouvez créer un plan de reprise après incident BCDR avec le cloud public, point de passage à un plan de reprise après incident transitoire ou à plein temps, tout en réduisant le coût de la solution de reprise après incident.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:gcp-ncvo-solution-validation.html["Précédent : validation de la solution."]

[role="lead"]
Dans cette solution, le service de données cloud NetApp, Cloud Volumes ONTAP et l'infrastructure de data Center FlexPod ont été utilisés pour créer une solution de reprise après incident avec un cloud public optimisé par Cisco Intersight Cloud Orchestrator. La solution FlexPod a constamment évolué pour permettre aux clients de moderniser leurs applications et leurs processus de distribution. Avec cette solution, vous pouvez créer un plan de reprise après incident BCDR avec le cloud public, point de passage à un plan de reprise après incident transitoire ou à plein temps, tout en réduisant le coût de la solution de reprise après incident.

La réplication des données entre FlexPod sur site et NetApp Cloud Volumes ONTAP a été gérée par la technologie SnapMirror éprouvée, mais vous pouvez également sélectionner d'autres outils NetApp de transfert et de synchronisation comme Cloud Sync pour vos besoins en termes de mobilité des données. Sécurité des données à la volée assurée par des technologies de chiffrement intégrées basées sur TLS/AES.

Que vous ayez un plan de reprise sur incident temporaire pour une application ou un plan de reprise sur incident à temps plein pour une entreprise, le portefeuille de produits utilisés dans cette solution peut répondre aux deux besoins à grande échelle. Optimisé par Cisco Intersight Workflow Orchestrator, il en va de même pour l'automatisation avec des flux de travail prédéfinis qui éliminent non seulement les processus de reconstruction, mais accélèrent également la mise en œuvre d'un plan de CDR.

Cette solution permet de gérer FlexPod sur site et la réplication des données dans un cloud hybride de manière très simple et pratique, grâce à l'automatisation et à l'orchestration fournies par Cisco Intersight Cloud Orchestrator.



[[where-to-find-additional-information]]
== Où trouver des informations complémentaires

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :



[[github]]
=== GitHub

* Toutes les configurations Terraform utilisées
+
https://github.com/ucs-compute-solutions/cvo_snapmirror["https://github.com/ucs-compute-solutions/cvo_snapmirror"^]

* Fichiers JSON pour l'importation des flux de production
+
https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows["https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows"^]





[[cisco-intersight]]
=== Cisco Intersight

* Centre d'aide Cisco Intersight
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* Documentation Cisco Intersight Cloud Orchestrator :
+
https://intersight.com/help/appliance/orchestration/configure["https://intersight.com/help/appliance/orchestration/configure"^]

* Cisco Intersight Service pour la documentation Terraform de HashiCorp
+
https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093["https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093"^]

* Fiche technique Cisco Intersight
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html"^]

* Fiche technique Cisco Intersight Cloud Orchestrator
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html"^]

* Fiche technique Cisco Intersight Service for HashiCorp Terraform
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html"^]





[[flexpod]]
=== FlexPod

* Page d'accueil de FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guides de conception et de déploiement validés par Cisco pour FlexPod
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["FlexPod Datacenter avec Cisco UCS 4.2(1) en mode géré UCS, VMware vSphere 7.0 U2 et NetApp ONTAP 9.9 : Guide de conception"^]

* FlexPod Datacenter avec Cisco UCS X-Series
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]





[[interoperability]]
=== Interopérabilité

* Matrice d'interopérabilité NetApp
+
http://mysupport.netapp.com/matrix["http://mysupport.netapp.com/matrix"^]

* Outil d'interopérabilité matérielle et logicielle Cisco UCS
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Guide de compatibilité VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





[[netapp-cloud-volumes-ontap-reference-documents]]
=== Documents de référence de NetApp Cloud Volumes ONTAP

* NetApp Console Documentation :
+
https://docs.netapp.com/us-en/console-family/index.html["https://docs.netapp.com/us-en/console-family/index.html"^]

* Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[]

* Calculateur de coût total de possession (TCO) de Google Cloud avec NetApp Cloud Volumes ONTAP
+
https://www.netapp.com/google-cloud/google-cloud-calculator/[]

* Dimensionnement et estimation des coûts de Cloud Volumes ONTAP :
+
https://www.netapp.com/ontap-cloud/pricing/["https://www.netapp.com/ontap-cloud/pricing/"^]

* Évaluation du cloud et analyse de l'infrastructure :
+
https://docs.netapp.com/us-en/data-infrastructure-insights/[]

* NetApp Solutions de cloud hybride :
+
https://www.netapp.com/hybrid-cloud/[]

* Documentation de l'API Cloud Manager
+
https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html["https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html"^]





[[troubleshooting-issues]]
=== Résolution des problèmes

https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs["https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs"^]



[[terraform]]
=== Terraform

* Terraform Cloud
+
https://www.terraform.io/cloud["https://www.terraform.io/cloud"^]

* Documentation Terraform
+
https://www.terraform.io/docs/["https://www.terraform.io/docs/"^]

* Registre NetApp Cloud Manager
+
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates["https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates"^]





[[gcp]]
=== GCP

* ONTAP haute disponibilité pour GCP
+
https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick["https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick"^]

* Avantages de GCP
+
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6["https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6"^]


