---
sidebar: sidebar 
permalink: vdi/fpd-citrix-xend-vmw.html 
keywords: cisco, flexpod, all, flash, aff, citrix, vmware, vsphere, stroage, esxi, hypervisor 
summary: 'Ce document présente l"architecture de référence pour la conception d"applications et de postes de travail virtuels à l"aide de Citrix XenApp/XenDesktop 7.15 basé sur Cisco UCS avec FAS un système de stockage NetApp AFF A300 et la plateforme d"hyperviseur VMware vSphere ESXi 6.5.' 
---
= FlexPod Datacenter avec Citrix XenDesktop/XenApp 7.15 et VMware vSphere 6.5 Update 1 pour 6 6000 postes
:allow-uri-read: 


Vadim Lebedev, Cisco Chris Rodriguez, NetApp

Ce document présente l'architecture de référence pour la conception d'applications et de postes de travail virtuels à l'aide de Citrix XenApp/XenDesktop 7.15 basé sur Cisco UCS avec FAS un système de stockage NetApp AFF A300 et la plateforme d'hyperviseur VMware vSphere ESXi 6.5.

L'environnement de la virtualisation des postes de travail et des applications évolue en permanence. Associés à l'infrastructure éprouvée FlexPod, les nouveaux serveurs lames Cisco UCS haute performance M5 et Cisco UCS Unified Fabric offrent AFF une plateforme plus compacte, plus puissante, plus fiable et plus efficace.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/cisco_ucs_xd715esxi65u1_flexpod.html["FlexPod Datacenter avec Citrix XenDesktop/XenApp 7.15 et VMware vSphere 6.5 Update 1 pour 6 6000 postes"^]
