---
sidebar: sidebar 
permalink: flexpod-dc/fpd-inter-design.html 
keywords: flexpod, cisco, ontap, intersight, cloud, vmware, vsphere, deployment 
summary: 'Ce document présente une solution validée pour le déploiement des technologies Cisco et NetApp en tant qu"infrastructure cloud partagée.' 
---
= FlexPod Datacenter avec Cisco Intersight et NetApp ONTAP 9.7 - conception
:allow-uri-read: 


John George, Cisco Scott Kovacs, NetApp

[role="lead"]
Ce document présente une solution validée pour le déploiement des technologies Cisco et NetApp en tant qu'infrastructure cloud partagée. Cette conception validée fournit une structure pour le déploiement de VMware vSphere, la plateforme de virtualisation la plus populaire dans les data centers d'entreprise, sur FlexPod.

L'infrastructure intégrée de pointe FlexPod prend en charge un large éventail de charges de travail et d'utilisations. Cette solution permet aux clients de déployer rapidement et de manière fiable un cloud privé basé sur VMware vSphere sur une infrastructure intégrée.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_dc_ontap_97_ucs_4_vmw_vs_67_U3_design.html["FlexPod Datacenter avec Cisco Intersight et NetApp ONTAP 9.7 - conception"^]
