---
sidebar: sidebar 
permalink: flexpod-dc/sm-bcs-where-to-find-additional-information-and-version-history.html 
keywords:  
summary:  
---
= Où trouver des informations supplémentaires et l'historique des versions
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:sm-bcs-conclusion.html["Précédent: Conclusion."]

Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :



== FlexPod

* Page d'accueil de FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guides de conception et de déploiement validés par Cisco pour FlexPod
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* Serveurs Cisco - Unified Computing System (UCS)
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html"^]

* Documentation produit NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* FlexPod Datacenter avec Cisco UCS 4.2(1) en mode géré UCS, VMware vSphere 7.0 U2 et NetApp ONTAP 9.9 : Guide de conception
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html"^]

* Guide de déploiement de FlexPod Datacenter avec Cisco UCS 4.2(1) en mode géré UCS, VMware vSphere 7.0 U2 et NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html"^]

* Guide de design de FlexPod Datacenter avec Cisco UCS X-Series, VMware 7.0 U2 et NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]

* Guide de déploiement de FlexPod Datacenter avec Cisco UCS X-Series, VMware 7.0 U2 et NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html"^]

* Guide de design de FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et baies NetApp AFF/FAS NVA
+
https://www.netapp.com/pdf.html?item=/media/22621-nva-1154-DESIGN.pdf[]

* Guide de déploiement de FlexPod Express pour VMware vSphere 7.0 avec Cisco UCS Mini et NVA AFF/FAS de NetApp
+
https://www.netapp.com/pdf.html?item=/media/21938-nva-1154-DEPLOY.pdf[]

* FlexPod MetroCluster IP avec structure front-end multisite VXLAN
+
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf["https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf"^]

* Boîte NAbox
+
https://nabox.org["https://nabox.org"^]

* Récolte NetApp
+
https://github.com/NetApp/harvest/releases["https://github.com/NetApp/harvest/releases"^]





== SM-BC

* SM-BC
+
https://docs.netapp.com/us-en/ontap/smbc/index.html["https://docs.netapp.com/us-en/ontap/smbc/index.html"^]

* Tr-4878 : continuité de l'activité SnapMirror (SM-BC) ONTAP 9.8
+
https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf"^]

* Comment supprimer correctement une relation SnapMirror ONTAP 9
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9["https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9"^]

* Principes de base de la reprise après incident synchrone de SnapMirror
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html"^]

* Principes de base de la reprise sur incident asynchrone SnapMirror
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html#data-protection-relationships"^]

* Protection des données et reprise d'activité
+
https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html"^]

* Installez ou mettez à niveau le service ONTAP Mediator
+
https://docs.netapp.com/us-en/ontap/mediator/index.html["https://docs.netapp.com/us-en/ontap/mediator/index.html"^]





== VMware vSphere HA et vSphere Metro Storage Cluster

* Création et utilisation de clusters HA vSphere
+
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html"^]

* Cluster de stockage Metro VMware vSphere (vMSC)
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc"^]

* Bonnes pratiques pour VMware vSphere Metro Storage Cluster
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices"^]

* NetApp ONTAP avec NetApp SnapMirror Business Continuity (SM-BC) avec VMware vSphere Metro Storage Cluster (vMSC). (83370)
+
https://kb.vmware.com/s/article/83370["https://kb.vmware.com/s/article/83370"^]

* Protégez les bases de données et les applications de niveau 1 avec VMware vSphere Metro Storage Cluster et ONTAP
+
https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636["https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636"^]





== Microsoft SQL et HammerDB

* Microsoft SQL Server 2019
+
https://www.microsoft.com/en-us/sql-server/sql-server-2019["https://www.microsoft.com/en-us/sql-server/sql-server-2019"^]

* Guide des meilleures pratiques de conception de Microsoft SQL Server sur VMware vSphere
+
https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf["https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf"^]

* Site Web HammerDB
+
https://www.hammerdb.com["https://www.hammerdb.com"^]





== Matrice de compatibilité

* Matrice de compatibilité matérielle Cisco UCS
+
https://ucshcltool.cloudapps.cisco.com/public/["https://ucshcltool.cloudapps.cisco.com/public/"^]

* Matrice d'interopérabilité NetApp
+
https://support.netapp.com/matrix/["https://support.netapp.com/matrix/"^]

* NetApp Hardware Universe
+
https://hwu.netapp.com["https://hwu.netapp.com"^]

* Guide de compatibilité VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Avril 2022 | Version initiale. 
|===