---
sidebar: sidebar 
permalink: security/flexpod-fips-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Remerciements, historique des versions et où trouver des informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-conclusion.html["Précédent: Conclusion."]

[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et sites web :

* Guide de configuration de la sécurité de la gamme Cisco MDS 9000 NX-OS
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/mds9000/sw/8_x/config/security/cisco_mds9000_security_config_guide_8x/configuring_fips.html#task_1188151[]

* Guide de configuration de la sécurité Cisco Nexus série 9000 NX-OS, version 9.3(x)
+
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/security/configuration/guide/b-cisco-nexus-9000-nx-os-security-configuration-guide-93x/m-configuring-fips.html[]

* Publication NetApp and Federal information Processing Standard (FIPS) 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* FIPS 140-2
+
https://fieldportal.netapp.com/content/902303[]

* Guide NetApp ONTAP 9 sur le renforcement du partenariat
+
https://www.netapp.com/us/media/tr-4569.pdf[]

* Guide d'alimentation du cryptage NetApp
+
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.pow-nve%2Fhome.html[]

* Fiche produit NVE et NAE
+
https://www.netapp.com/us/media/ds-3899.pdf[]

* Fiche technique NSE
+
https://www.netapp.com/us/media/ds-3213-en.pdf[]

* Centre de documentation ONTAP 9
+
http://docs.netapp.com[]

* Publication NetApp and Federal information Processing Standard (FIPS) 140-2
+
https://www.netapp.com/company/trust-center/compliance/fips-140-2/[]

* Conformité Cisco et FIPS 140-2
+
https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html[]

* Module de chiffrement NetApp
+
https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2648.pdf[]

* Cybersécurité pour les moyennes et grandes organisations dans le domaine de la santé
+
https://www.phe.gov/Preparedness/planning/405d/Documents/tech-vol2-508.pdf[]

* Programme de validation Cisco et module cryptographique (CMVP)
+
https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&Vendor=cisco&CertificateStatus=Active&ValidationYear=0[]

* NetApp Storage Encryption, disques avec autocryptage NVMe, NetApp Volume Encryption et NetApp Aggregate Encryption
+
https://www.netapp.com/pdf.html?item=/media/17073-ds-3898.pdf[]

* NetApp Volume Encryption et chiffrement d'agrégat NetApp
+
https://www.netapp.com/pdf.html?item=/media/17070-ds-3899.pdf[]

* NetApp Storage Encryption
+
https://www.netapp.com/pdf.html?item=/media/7563-ds-3213-en.pdf[]

* FlexPod pour les systèmes de dossiers médicaux électroniques
+
https://www.netapp.com/pdf.html?item=/media/22199-tr-4881.pdf[]

* Disponibilité immédiate des données : améliorer les performances dans les environnements de DME EPIC grâce à la technologie Flash connectée au cloud
+
https://www.netapp.com/media/10809-cloud-connected-flash-wp.pdf[]

* FlexPod Datacenter pour infrastructure EHR Epic
+
https://www.netapp.com/pdf.html?item=/media/17061-ds-3683.pdf[]

* Guide de déploiement de FlexPod Datacenter pour Epic EHR
+
https://www.netapp.com/media/10658-tr-4693.pdf[]

* Infrastructure de data Center FlexPod pour le logiciel MEDITECH
+
https://www.netapp.com/media/8552-flexpod-for-meditech-software.pdf[]

* La norme FlexPod s'étend au logiciel MEDITECH
+
https://blog.netapp.com/the-flexpod-standard-extends-to-meditech-software/[]

* FlexPod pour MEDITECH : Guide de dimensionnement
+
https://www.netapp.com/pdf.html?item=/media/12429-tr4774.pdf[]

* FlexPod pour l'imagerie médicale
+
https://www.netapp.com/media/19793-tr-4865.pdf[]

* L'IA dans le domaine de la santé
+
https://www.netapp.com/us/media/na-369.pdf[]

* FlexPod pour le secteur de la santé facilite votre transformation
+
https://flexpod.com/solutions/verticals/healthcare/[]

* FlexPod de Cisco et NetApp
+
https://flexpod.com/[]





== Remerciements

* Abhinav Singh, Ingénieur marketing et technique, NetApp
* Brian O’Mehony, architecte de solutions au sein du secteur de la santé (Epic), NetApp
* Brian Pruitt, responsable du développement commercial chez NetApp
* Arvind Ramakrishnan, architecte de solutions senior, NetApp
* Michael Hommer, Directeur technique mondial chez FlexPod, NetApp




== Historique des versions

|===
| Version | Date | Historique des versions du document 


| Version 1.0 | Avril 2021 | Version initiale 
|===