---
sidebar: sidebar 
permalink: ent-db/fpd-sap-aseries-design.html 
keywords: flexpod, cisco, sap, intel, ucs, aff, a-series, nexus 9000 
summary: 'Ce document décrit la méthodologie de déploiement de Cisco et NetApp FlexPod Datacenter pour SAP HANA basée sur la deuxième génération de processeurs Intel Xeon Scalable compatibles avec Cisco UCS Computing System (Cisco UCS).' 
---
= Centre de données FlexPod pour solution SAP avec Cisco UCS, fabric de troisième génération et NetApp AFF A-Series
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

Ce document décrit la méthodologie de déploiement de Cisco et NetApp FlexPod Datacenter pour SAP HANA basée sur la deuxième génération de processeurs Intel Xeon Scalable compatibles avec Cisco UCS Computing System (Cisco UCS).

Cisco UCS Manager (UCSM) 4.0(4) assure la prise en charge consolidée de tous les modèles Cisco UCS Fabric Interconnect (6200, 6300, 6324 et 6454), d'un module de la gamme 2200/2300, d'un serveur lame Cisco UCS B-Series et de serveurs rack Cisco UCS C-Series. Le data Center FlexPod, associé au logiciel unifié Cisco UCS version 4.0(4d) et à NetApp ONTAP 9.6, est une architecture de data Center prédéfinie et basée sur les meilleures pratiques. Elle repose sur Cisco UCS, la gamme de commutateurs Cisco Nexus 9000 et les baies de stockage NetApp AFF A-Series.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_sap_ontap96.html["Centre de données FlexPod pour solution SAP avec Cisco UCS, structure de troisième génération et NetApp AFF A-Series"^]
