---
sidebar: sidebar 
permalink: ent-db/fpd-sap-cisco-aci-deploy.html 
keywords: flexpod, cisco, sap, hana, ucs, aff, a-series, aci 
summary: 'Ce document présente les procédures d"architecture et de déploiement de l"option SAP HANA Tailored datacenter Integration sur une infrastructure FlexPod' 
---
= Centre de données FlexPod pour SAP avec Cisco ACI, Cisco UCS Manager 4.0, et NetApp AFF A-Series - déploiement
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

[role="lead"]
Ce document présente les procédures d'architecture et de déploiement de l'option SAP HANA Tailored datacenter Integration sur une infrastructure FlexPod, qui se compose des éléments suivants :

* Cisco UCS Computing System (Cisco UCS) pris en charge par la deuxième génération de processeurs Intel Xeon Scalable.
* Commutation de produits qui utilisent l'ACI (application Centric Infrastructure) de Cisco.
* Baies AFF NetApp A-Series


L'objectif de ce document est de présenter les étapes de configuration détaillées du déploiement de SAP HANA

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_ACI_sap_netappaffa.html["Centre de données FlexPod pour SAP avec Cisco ACI, Cisco UCS Manager 4.0, et NetApp AFF A-Series - déploiement"^]
