---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql.html 
keywords: flexpod, cisco, white, paper,sap, non-hana, sql 
summary: Le secteur INFORMATIQUE actuel connaît une transformation radicale des solutions de data Center. 
---
= SAP non-HANA avec SQL - Design
:allow-uri-read: 


[role="lead"]
Le secteur INFORMATIQUE actuel connaît une transformation radicale des solutions de data Center. Ces dernières années, les solutions de data Center prévalidées et spécialisées ont suscité un intérêt considérable. L'introduction de technologies de virtualisation dans des domaines critiques a eu un impact majeur sur les principes de conception et l'architecture de ces solutions. Elle a permis à de nombreuses applications s'exécutant sur des systèmes bare-Metal de migrer vers de nouvelles solutions intégrées virtualisées. FlexPod est une solution de data Center prévalidée et spécialisée conçue pour répondre à l'évolution rapide des besoins des services IT. Cisco et NetApp se sont associés pour proposer FlexPod, qui utilise les meilleurs composants de calcul, de réseau et de stockage pour la base de nombreux workloads d'entreprise, notamment les bases de données, la planification des ressources d'entreprise (ERP), la gestion de la relation client (CRM) et les applications web.

La consolidation des applications IT, en particulier des bases de données, a suscité un intérêt considérable ces dernières années. Microsoft SQL Server est la plateforme de base de données la plus utilisée et la plus déployée au cours des dernières années. Les bases de données SQL Server sont souvent confrontées à la prolifération des bases de données, ce qui entraîne des défis INFORMATIQUES tels que des serveurs sous-utilisés, des licences incorrectes, des problèmes de sécurité, des problèmes de gestion et des coûts d'exploitation colossaux. Par conséquent, les bases de données SQL Server sont de bons candidats à la consolidation sur une plateforme plus robuste, plus flexible et plus résiliente. Ce document présente une architecture de référence FlexPod pour le déploiement et la consolidation des bases de données SQL Server.

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["SAP non-HANA avec SQL - Design"^]
