---
sidebar: sidebar 
permalink: ent-db/fpd-sap-aci-aseries-design.html 
keywords: flexpod, cisco, sap, aci, UCS manager, aff, a-series, tdi, sap, hana 
summary: 'Ce document présente la solution FlexPod intégrée de l"ACI Cisco comme une approche validée pour le déploiement des environnements SAP HANA TDI (Tailored Data Center Integration).' 
---
= Centre de données FlexPod pour la solution SAP avec Cisco ACI, Cisco UCS Manager 4.0 et NetApp AFF A-Series - Design
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

[role="lead"]
Ce document présente la solution FlexPod intégrée de l'ACI Cisco comme une approche validée pour le déploiement des environnements SAP HANA TDI (Tailored Data Center Integration). Cette conception validée fournit des instructions et un cadre pour l'implémentation de SAP HANA avec les bonnes pratiques de Cisco et NetApp.

L'architecture de solution recommandée repose sur Cisco Unified Computing System (Cisco UCS) à l'aide d'une version logicielle unifiée qui prend en charge les plateformes matérielles Cisco UCS incluant les composants suivants :

* Les serveurs lames Cisco UCS B-Series et les serveurs rack Cisco UCS C-Series peuvent être configurés avec l'option DCPMM (Data Center persistent Memory module) d'Intel Optane
* Cisco UCS 6400 Series Fabric Interconnect
* Commutateurs lame et spine Cisco Nexus série 9000
* Baies de stockage de la gamme 100 % Flash de NetApp


En outre, ce document fournit des validations pour Red Hat Enterprise Linux et SUSE Linux Enterprise Server pour SAP HANA.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_ACI_sap_netappaffa_design.html["Centre de données FlexPod pour la solution SAP avec Cisco ACI, Cisco UCS Manager 4.0 et NetApp AFF A-Series - Design"^]
