---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql-deploy.html 
keywords: flexpod, cisco, sap, sql, servers, data, bases 
summary: 'FlexPod est une solution de data Center spécialisée et prévalidée conçue pour répondre à l"évolution rapide des besoins des services IT.' 
---
= Déployez des serveurs d'applications SAP sur FlexPod avec SQL
:allow-uri-read: 


[role="lead"]
FlexPod est une solution de data Center spécialisée et prévalidée conçue pour répondre à l'évolution rapide des besoins des services IT. Cisco et NetApp se sont associés pour proposer FlexPod, qui utilise les meilleurs composants de calcul, de réseau et de stockage pour la base de nombreux workloads d'entreprise, notamment les bases de données, la planification des ressources d'entreprise (ERP), la gestion de la relation client (CRM) et les applications web. La consolidation des applications IT, en particulier des bases de données, a suscité un intérêt considérable ces dernières années. Microsoft SQL Server est la plateforme de base de données la plus utilisée et la plus déployée au cours des dernières années. Les bases de données SQL Server sont souvent confrontées à la prolifération des bases de données, ce qui entraîne des défis INFORMATIQUES tels que des serveurs sous-utilisés, des licences incorrectes, des problèmes de sécurité, des problèmes de gestion et des coûts d'exploitation colossaux. Par conséquent, les bases de données SQL Server sont de bons candidats à la consolidation sur une plateforme plus robuste, plus flexible et plus résiliente. Ce document présente une architecture de référence FlexPod pour le déploiement et la consolidation des bases de données SQL Server.

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["Déployez des serveurs d'applications SAP sur FlexPod avec SQL"^]
