---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 'Vérifier que vous répondez aux exigences en matière de matériel, de logiciels et de licences pour l"intégration du stockage NetApp ONTAP avec Cisco InterSight.' 
---
= De formation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Vérifier que vous répondez aux exigences en matière de matériel, de logiciels et de licences pour l'intégration du stockage NetApp ONTAP avec Cisco InterSight.



== Configuration matérielle et logicielle requise

Il s'agit des composants matériels et logiciels minimum requis pour implémenter la solution. Ils peuvent varier selon la mise en œuvre de la solution et les besoins du client.

|===
| Composant | Détails de l'exigence 


| NetApp ONTAP | ONTAP 9.7P1 et versions ultérieures 


| NetApp Active IQ Unified Manager | La dernière version de NetApp Active IQ Unified Manager est requise (actuellement 9.13GA) 


| Baie de stockage NetApp | Toutes les baies de stockage ONTAP ASA, AFF et FAS sont prises en charge pour ONTAP 9.7P1 et versions ultérieures 


| Hyperviseur de virtualisation | VSphere 6.7 et versions ultérieures 
|===

NOTE: Reportez-vous à la section https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/flexpod/cisco-imm-for-flexpod.html["Mode géré Cisco Intersight pour FlexPod"^] Pour les exigences minimales des composants de calcul Cisco UCS et de la version UCSM.



== Conditions requises pour les licences Cisco Intersight

Cisco Intersight dispose d'une licence sur la base d'un abonnement avec plusieurs éditions de licence à choisir. Les capacités évoluent avec les différents types de licence. Vous pouvez acheter une durée d'abonnement de un, trois ou cinq ans et choisir le niveau de volume Cisco UCS Server requis pour la durée d'abonnement sélectionnée. Chaque terminal Cisco inclut automatiquement une base Cisco Intersight sans frais supplémentaires lorsque vous accédez au portail Cisco Intersight et demandez un périphérique.

Vous pouvez acheter l'une des licences Intersight de niveau supérieur suivantes à l'aide de l'outil de commande Cisco :

* *Cisco Intersight Essentials.* Essentials inclut toutes les fonctionnalités du niveau de base avec les fonctions supplémentaires, notamment les droits Cisco UCS Central et Cisco IMC Supervisor, la configuration basée sur des règles avec profils de service, la gestion du micrologiciel et l'évaluation de la compatibilité avec la liste de compatibilité matérielle (HCL).
* *Cisco Intersight Advantage.* Advantage offre toutes les fonctionnalités des niveaux base et Essentials. Il comprend les widgets de stockage, l'inventaire du stockage, la capacité de stockage et l'utilisation du stockage, ainsi que la corrélation d'inventaire interdomaine sur le calcul physique, le stockage physique et les environnements virtuels (VMware ESXi).
* *Cisco Intersight Premier.* en plus des fonctionnalités du niveau Advantage, Cisco Intersight Premier offre une orchestration IaaS (Private Cloud Infrastructure-as-a-Service) sur Cisco UCS et des systèmes tiers, notamment des machines virtuelles (VM) (VMware vCenter) et du stockage physique (stockage NetApp).


Pour plus d'informations sur les fonctionnalités couvertes par les différents niveaux de licence, accédez à https://intersight.com/help/getting_started#intersight_licensing["Licences Cisco"].
