---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 'Vérifier que vous répondez aux exigences en matière de matériel, de logiciels et de licences pour l"intégration du stockage NetApp ONTAP avec Cisco InterSight.' 
---
= De formation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Vérifiez que vous respectez les exigences en matière de matériel, de logiciels et de licences pour l'intégration du stockage NetApp ONTAP dans Cisco Intersight.



== Configuration matérielle et logicielle requise

Il s'agit des composants matériels et logiciels minimum requis pour implémenter la solution. Ils peuvent varier selon la mise en œuvre de la solution et les besoins du client.

|===
| Composant | Détails de l'exigence 


| NetApp ONTAP | ONTAP 9.7P1 et versions ultérieures 


| NetApp Active IQ Unified Manager | La dernière version de NetApp Active IQ Unified Manager est requise (actuellement 9.14RC1) 


| Baie de stockage NetApp | Toutes les baies de stockage ONTAP ASA, AFF et FAS sont prises en charge pour ONTAP 9.7P1 et versions ultérieures 


| Hyperviseur de virtualisation | VSphere 7.0 et versions ultérieures 
|===

NOTE: Reportez-vous à la section https://intersight.com/help/saas/supported_systems["Systèmes pris en charge par Cisco Intersight"^] Pour les exigences minimales des composants de calcul Cisco UCS et de la version UCSM.



== Conditions requises pour les licences Cisco Intersight

Cisco Intersight propose des services tels que le service d'infrastructure et le service d'orchestration cloud pour gérer, automatiser et optimiser le stockage physique (stockage NetApp). Vous pouvez utiliser ces services pour gérer le serveur Cisco UCS et le système Cisco HyperFlex. Le service d'infrastructure et le service Cloud Orchestrator utilisent un modèle de licence par abonnement avec plusieurs tiers. Vous pouvez choisir le niveau de volume de serveur Cisco UCS requis pour la période d'abonnement sélectionnée.

.Modèle de licence
Le modèle de licence des services d'infrastructure Cisco Intersight a été simplifié et offre désormais les deux tiers suivants :

* *Cisco Intersight Infrastructure Services Essentials* - le niveau de licence Essentials offre la gestion du serveur, y compris la fonctionnalité de surveillance de l'état global, l'inventaire, la prise en charge proactive via l'intégration Cisco TAC, l'authentification multifacteur, ainsi que l'accès au SDK et à l'API.
* *Cisco Intersight Infrastructure Services Advantage* - le niveau de licence Advantage offre une gestion avancée des serveurs avec une visibilité étendue, l'intégration de l'écosystème, l'automatisation du matériel et des logiciels Cisco et tiers, ainsi que des solutions multi-domaines.


Pour plus d'informations sur les fonctionnalités couvertes par les différents niveaux de licence, accédez à https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["Licence Infrastructure Services"^].
