---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_new.html 
keywords: 'netapp, cisco, ontap, intersight, flexpod, what"s new, features, release notes, enhancements' 
summary: Cisco Intersight propose de nouvelles versions pour vous apporter de nouvelles fonctionnalités, améliorations et correctifs. 
---
= Quoi de neuf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cette section répertorie les nouvelles fonctionnalités disponibles pour Cisco Intersight avec le stockage NetApp ONTAP.



== Novembre 2023


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.14RC1 est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités avec la dernière version.

* Ajout de la page Namespaces NVMe dans la section Inventory de l'interface utilisateur.




== Août 2023


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.13GA est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités avec la dernière version.

* Amélioration de la tâche New NetApp Smart LUN pour indiquer clairement la disponibilité des options de sélection permettant de créer un nouveau groupe initiateur ou de sélectionner un groupe initiateur existant. Lorsque les utilisateurs sélectionnent la zone pour créer un nouveau groupe initiateur, le paramètre permettant de choisir un groupe initiateur existant n'est plus disponible. Si les utilisateurs désélectionnez la case pour créer un nouveau groupe initiateur, le paramètre du groupe initiateur existant devient disponible.
* Amélioration des tâches Nouveau mappage de LUN NetApp et Supprimer le mappage de LUN NetApp - effectué. La nouvelle relation entre la LUN et le groupe initiateur est maintenant mise à jour. L'inventaire de l'interface utilisateur est immédiatement mis à jour pour la LUN et le groupe initiateur lors de l'exécution de la tâche.
* La page vérifications se charge maintenant correctement lors de la première connexion des utilisateurs et ne nécessite plus d'actualisation.




== Juillet 2023


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.13GA est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités avec la dernière version.

* Noms mis à jour pour les tâches de stockage NetApp. Voir cas d'utilisation 3 flux de travail personnalisés à l'aide d'un formulaire sans concepteur pour la liste complète des tâches renommées.
* L'adresse IP de l'interface NFS a été ajoutée en tant que sortie de la tâche Nouveau volume intelligent NAS NetApp.
* Vérifiez que le transport ASUP est HTTPS a été ajouté à l'onglet vérifications.
* Le type de niveau correct pour tous les niveaux s'affiche désormais correctement sous l'interface utilisateur tiers.
* Toutes les licences compatibles s'affichent désormais correctement dans la page licences.
* La valeur exacte des partages CIFS sans ou sans répertoire personnel s'affiche désormais sur la page partages.
* Le tri et le filtrage sont désormais activés pour la colonne mappée sur la page LUN.
* Le tri et le filtrage ont maintenant activé la colonne authentification activée sur la page serveurs NTP.
* Ajout de nouvelles vérifications et des catégories correspondantes suivantes à l'onglet vérifications.
+
** Sécurité
** Anti-ransomware
** Disponibilité
** Autre


* Dans la vue détaillée Inventaire, le rapport est maintenant utilisé au lieu de la capacité physique utilisée.




== Juin 2023


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.13RC1 est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités avec la dernière version.

* Noms mis à jour pour les tâches de stockage NetApp. Voir link:ci-qsg_use_cases.html["Cas d'utilisation 3 workflows personnalisés à l'aide d'un formulaire sans concepteur"^] pour la liste complète des tâches renommées.




== Avril 2023

* Ajout des onglets protection Policies (SnapMirror) et Snapshot Policies dans la page Policies de la section Inventory de l'interface utilisateur.
* Ajout de la page clients NFS sous la section Inventaire de l'interface utilisateur.
* Ajout de la colonne protégé dans la page machines virtuelles de stockage sous la section Inventaire de l'interface utilisateur.
* Modification du mode de rapport et d'affichage des informations de réduction des données.
* Ajout des onglets local Tier et Cloud Tier sous la page tiers dans la section Inventaire de l'interface utilisateur.
* La colonne nœud s'affiche désormais après la colonne Nom sous la page ports de la section Inventaire de l'interface utilisateur.




== Janvier 2023


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.12 GA est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités de la dernière version. Pour obtenir la liste des problèmes connus liés à cette version, reportez-vous à la section <<Problèmes connus>>.

* Les contrôles d'interopérabilité Intersight permettent désormais de distinguer les modes de microprogramme de l'UCSM et de l'IMM lors de l'exécution des contrôles de compatibilité.
* Les relations de protection ne s'afficheront pas dans Intersight pour ONTAP 9.7. Ce problème a été résolu dans la version ONTAP 9.8RC1.




== Août 2022


NOTE: Une mise à niveau vers NetApp Active IQ Unified Manager 9.11 GA est nécessaire pour garantir la compatibilité et l'intégralité des fonctionnalités de la dernière version. Pour obtenir la liste des problèmes connus liés à cette version, reportez-vous à la section <<Problèmes connus>>.

* Calcul de la capacité disponible du cluster mis à jour pour correspondre à System Manager
* Page général du cluster mise à jour pour masquer le récapitulatif des mesures de performances jusqu'à ce que les données de performances soient renseignées
* Résolution d'un problème lié à l'interface utilisateur de la page générale du cluster qui a occasionnellement provoqué l'arrêt de la page
* Ajout de partages CIFS, de services CIFS, de qtrees et de règles SnapMirror SVM à l'inventaire interne.
* Partages et qtrees ajoutés au menu de navigation de l'interface utilisateur, sous la section Logical Inventory (Inventaire logique)
* Partages ajoutés sous forme d'onglet à partir d'une VM de stockage sélectionnée
* Ajout d'informations sur le service CIFS dans l'onglet général de la machine virtuelle de stockage si la machine virtuelle de stockage est activée par CIFS
* Ajout d'une page de vérification de cluster qui permet aux utilisateurs de valider la configuration des systèmes de stockage NetApp conformément aux meilleures pratiques




== Juillet 2022

* Des graphismes améliorés pour le ratio de réduction des données du cluster sont désormais disponibles dans le widget capacité
* Ajout de l'onglet interfaces FC à la page interfaces réseau
* La création d'un nouveau volume à l'aide de la tâche générique "Nouveau volume de stockage" définit maintenant la garantie d'espace volume sur aucun et le pourcentage de réserve snapshot sur 0%
* Le champ Commentaire de la tâche Modifier la stratégie Snapshot est maintenant facultatif et n'est plus obligatoire
* Inventaire de l'interface et cohérence de l'orchestration améliorées
* Les informations de capacité Intersight sous capacité du cluster sont désormais cohérentes avec System Manager
* Case à cocher ajoutée sous la tâche Nouvelle machine virtuelle de stockage pour afficher tous les paramètres lors de la création d'une nouvelle interface de gestion afin d'améliorer la convivialité
* Protocoles déplacés en dessous de la correspondance du client, désormais compatibles avec System Manager
* Page générale de la règle d'exportation affichant maintenant le ou les protocoles d'accès
* suppression d'igroup désormais enregistrée de manière conditionnelle
* Ajout des paramètres « Failover Policy » et « autorevert » pour NAS sous Nouvelle interface de données Storage NAS et Nouvelle interface de données Storage iSCSI
* La restauration de la tâche New Storage NAS Smart Volume supprime désormais la stratégie d'exportation si aucun autre volume n'est associé
* Améliorations apportées aux tâches Smart Volume et Smart LUN




== Avril 2022


NOTE: Pour assurer la compatibilité et une fonctionnalité complète avec les prochaines versions, il est recommandé de mettre à niveau votre Active IQ Unified Manager vers la version 9.10P1.

* Ajout de la page Broadcast Domain à Ethernet Port Detail
* A modifié le terme « agrégat » en « Tier » pour l'agrégat et la SVM au sein de l'interface utilisateur
* Le terme « État du cluster » est passé à « État de la baie »
* Le filtre MTU fonctionne maintenant pour les caractères <,>,=,<=,>=
* Ajout de la page d'interface réseau à l'inventaire du cluster
* Ajout de AutoSupport à l'inventaire du cluster
* Ajouté `cdpd.enable` option vers le nœud
* Ajout d'un objet pour le voisin CDP
* Ajout des tâches de stockage des flux de travail NetApp dans Cisco InterSight. Voir link:ci-qsg_use_cases.html["Cas d'utilisation 3 workflows personnalisés à l'aide d'un formulaire sans concepteur"^] Vous trouverez une liste complète des tâches de stockage NetApp.




== Janvier 2022

* Ajout d'alarmes Intersight basées sur les événements pour NetApp Active IQ Unified Manager 9.10 ou version ultérieure.



NOTE: Pour assurer la compatibilité et une fonctionnalité complète dans les prochaines versions, nous vous recommandons de mettre à niveau votre Active IQ Unified Manager NetApp vers la version 9.10.

* Définissez explicitement chaque protocole activé (vrai ou faux) pour Storage Virtual machine
* État clusterHealthStatus mappé ok-avec suppression sur OK
* Colonne Santé renommée dans la colonne État du cluster, sous la page de liste Cluster List
* Affichage de la matrice de stockage « inaccessible » si le cluster est arrêté ou inaccessible
* Colonne Santé renommée dans la colonne État de la matrice sous la page général du cluster
* Le SVM dispose désormais d'un onglet « volumes » qui affiche tous les volumes du SVM
* Le volume dispose d'une section de capacité de snapshot
* Les licences s'affichent maintenant correctement




== Octobre 2021

* Liste mise à jour des tâches de stockage NetApp disponibles dans Cisco Intersight. Voir link:ci-qsg_use_cases.html["Cas d'utilisation 3 workflows personnalisés à l'aide d'un formulaire sans concepteur"^] Vous trouverez une liste complète des tâches de stockage NetApp.
* Ajout de la colonne Santé sous la page liste des clusters.
* Des détails étendus sont désormais disponibles sous la page général pour un groupe sélectionné.
* Le tableau du serveur NTP est désormais accessible via le volet de navigation.
* Ajout d'un nouvel onglet capteurs contenant la page général de la machine virtuelle de stockage.
* Résumé des groupes VLAN et d'agrégation de liens maintenant disponible sous la page Port General.
* Capacité totale des données ajoutée sous le tableau Volume Total Capacity.
* Colonnes latence, IOPS et débit ajoutées sous Statistiques de volume moyennes, Statistiques de LUN moyennes, Statistiques moyennes sur l'agrégat, Statistiques moyennes sur les machines virtuelles de stockage et statistiques moyennes sur les nœuds
+

NOTE: Les metrics de performance ci-dessus ne sont disponibles que pour les baies de stockage contrôlées par le biais de NetApp Active IQ Unified Manager 9.9 ou version ultérieure.





== Problèmes connus

* Si vous utilisez une version d'AIQUM 9.11 ou antérieure, un écart se produit entre les valeurs affichées sur la page liste de stockage et le graphique à barres de capacité de la page général de stockage. Pour résoudre ce problème, passez à AIQUM 9.12 ou supérieur pour garantir la précision des valeurs de capacité affichées.
* Si vous utilisez AIQUM 9.11 ou une version antérieure, toute vérification effectuée par l'onglet « interopérabilité » de la page « systèmes intégrés » ne permettra pas de distinguer précisément les composants IMM et UCSM Cisco. Pour résoudre ce problème, passez à AIQUM 9.12 pour vous assurer que tous les composants sont correctement identifiés.
* Pour garantir que les données d'inventaire du stockage Intersight ne sont pas affectées pendant le processus de collecte des données, tous les clusters ONTAP non pris en charge (c'est-à-dire les versions inférieures à ONTAP 9.7P1) doivent être supprimés de l'application Active IQ Unified Manager (AIQUM).
* Pour que toutes les cibles revendiquées puissent être correctement exécutées, il faut au moins une version AIQUM de 9.11 pour que les requêtes d'interopérabilité du système intégré FlexPod soient exécutées.
* La page vérifications de l'inventaire de stockage ne s'affiche pas si le cluster ONTAP est ajouté à AIQUM à l'aide d'un nom de domaine complet. Les utilisateurs doivent ajouter des clusters ONTAP à AIQUM à l'aide d'une adresse IP.

